### ISSUE TITLE
XGraphics.DrawMatrixCode ignores XBrush parameter

### ISSUE THREAD

**Issue by brandengunn** [empira/PDFsharp#10]
## Expected Behavior
- 1D codes (derived from BarCode) use provided XBrush when rendering (e.g. via XGraphics.DrawBarCode).
- 2D codes (derived from MatrixCode) use provided XBrush when rendering (e.g. via XGraphics.DrawMatrixCode).

## Actual Behavior
- 1D codes correctly use provided XBrush when rendering.
- 2D codes use XBrushes.Black when rendering.

## Steps to Reproduce the Behavior
- MCVE [Issue.zip](https://github.com/empira/PDFsharp/files/11436365/Issue.zip)

**Comment by ThomasHoevel** [comment]
Thanks for your feedback.

Beginning with the next preview, probably 6.0.0-preview-3, the 2D code will use the brush supplied in the call.

Note for others: 2D codes currently work with the GDI build only.
