### ISSUE TITLE
How to convert Byte[] to XImage in PdfSharp

### ISSUE THREAD

**Issue by Adhikesevan** [empira/PDFsharp#100]
I have used gfx.DrawBarCode() method to draw the QR code in PDF document but its not working.  I have shared the drawing code for your reference.

# Reporting an Issue Here
## Expected Behavior
The  Bar code (QR -Code) is needs to be generated for the CodeType 'DataMatrix' and its need to be drawn in the Pdf by using the DrawBarcode method.  

## Actual Behavior
Throws InvalidEnumArgumentException while creating the DataMatrix bar code . 

## Steps to Reproduce the Behavior

`var gfx = XGraphics.FromPdfPage(pdf.Pages[0], XPageDirection.Downwards);
BarCode barCode = BarCode.FromType(CodeType.DataMatrix, "Sample QR Text");
gfx.DrawBarCode(barCode, new XPoint(0, 0));
`

![image](https://github.com/empira/PDFsharp/assets/84829401/5f0fed50-b7a7-48b6-b514-c2bfd1466c04)

**Comment by palanisamy-emis** [comment]
@ThomasHoevel could you please have a look at the above query. We need a solution for this. Thanks

**Comment by ThomasHoevel** [comment]
See here:
https://stackoverflow.com/a/22323300

**Comment by Adhikesevan** [comment]
HI @ThomasHoevel ,

While using the suggestion in the [link](https://stackoverflow.com/a/22323300) itself throwing an error like "The given data and encoding combination is too big for the matrix size.", Do you have an working sample for this?

![image](https://github.com/empira/PDFsharp/assets/84829401/ff9d6dec-f45a-4bce-b55b-181a5c8f8032)
