### ISSUE TITLE
DrawMatrixCode seems to be returns null always in .Net8

### ISSUE THREAD

**Issue by Adhikesevan** [empira/PDFsharp#101]
I have used the code to draw the QR code in pdfsharp.

# Reporting an Issue Here
## Expected Behavior
Need to draw the barcode matrix.
## Actual Behavior
Throwing System.InvalidOperationException: ''XImage' must not be null here.' exception,
![image](https://github.com/empira/PDFsharp/assets/84829401/eaf2af4b-f0b2-4b02-9f50-4dafd27a2415)

**Comment by ThomasHoevel** [comment]
You need the GDI build of PDFsharp to draw matrix codes.
