### ISSUE TITLE
How to access to TextAlign for PdfSharp.Pdf.AcroForms.PdfTextField?

### ISSUE THREAD

**Issue by biapar** [empira/PDFsharp#108]
Version 6.1 prev 2

I see in the doc that it's possible to use TextAlign on a PDFField. I tried but I don't see the property.
Why?

Thanks.

**Comment by ThomasHoevel** [comment]
Do you have a link to the doc?

**Comment by biapar** [comment]
https://packdat.github.io/PDFsharp-net6/ApiDoc/pdfsharp.pdf.acroforms.textalignment

**Comment by ThomasHoevel** [comment]
That link does not refer to our repository. Derived versions can have modifications not available in the original version.

**Comment by biapar** [comment]
Ops..Sorry...I don't see that it was a fork! So it's not possible to change the alignment.
