### ISSUE TITLE
Migradoc: Issue using cloned Table

### ISSUE THREAD

**Issue by SmeeDee77** [empira/PDFsharp#110]
I have an issue when trying to use cloned tables in Migradoc.

See attached ZIP File, where a table and a corresponding cloned instance shall be added to the document in Migradoc .

Problem: For the DOM, properties of elements of a cloned table seem to be incorrectly assigned.
-> e.g. Property row.Table is null for all rows of the cloned table.
-> As a result, an exception is thrown during rendering of the cloned table.

[IssueWithClonedTable.zip](https://github.com/empira/PDFsharp/files/15146897/IssueWithClonedTable.zip)

P.S.: Thanks for your excellent work on Migradoc and PDFSharp !!!

**Comment by TH-Soft** [comment]
See #68.
Fixed with PDFsharp 6.1.0 Preview 3, release date not yet known, but coming soon.
Thanks for your feedback.
