### ISSUE TITLE
How to use Chinese fonts？

### ISSUE THREAD

**Issue by HmgsLJ** [empira/PDFsharp#114]
First thanks to the author for providing a good library, but I had a problem with version 6.0, that is, using Chinese fonts will make an error, what can I do to solve it.

Error：
```
System.InvalidOperationException:“No appropriate font found for family name '宋体'. Implement IFontResolver and assign to 'GlobalFontSettings.FontResolver' to use fonts.”
```

Code：
```
           // 创建一个新的PDF文档
           using (PdfDocument document = new PdfDocument())
           {
               // 添加一页
               PdfPage page = document.AddPage();
               XGraphics gfx = XGraphics.FromPdfPage(page);
               // 加载字体
               //XFont font = new XFont("simsun.ttc", 12, XFontStyleEx.Regular);
               XFont font = new XFont("宋体", 12, XFontStyleEx.Regular);

               // 绘制中文文本
               gfx.DrawString("你好，世界！", font, XBrushes.Black, new XRect(50, 50, page.Width, page.Height), XStringFormats.TopLeft);

               // 保存PDF文档
               string outputPath = "D://output.pdf";
               document.Save(outputPath);
           }
```

**Comment by ThomasHoevel** [comment]
The answer to your question is in the error message: Implement `IFontResolver` or use either the GDI or WPF build.

See also:  
https://docs.pdfsharp.net/PDFsharp/Topics/Fonts/About.html

**Comment by HmgsLJ** [comment]
> 问题的答案在错误消息中：实现或使用 GDI 或 WPF 生成。`IFontResolver`
> 
> 另请参阅：https://docs.pdfsharp.net/PDFsharp/Topics/Fonts/About.html

Yes, I saw it, felt my stupidity, the problem was solved, implementing IFontResolver fixed the problem

**Comment by ThomasHoevel** [comment]
No need to feel stupid. This is a breaking change that needs some explanation and we are trying to improve this error message even further.

**Comment by HmgsLJ** [comment]
> No need to feel stupid. This is a breaking change that needs some explanation and we are trying to improve this error message even further.

Thank you .

**Comment by Varorbc** [comment]
@HmgsLJ 你好,我也遇到了一样的问题,你是怎么解决的,我使用你的示例,然后实现了IFontResolver接口,运行后就提示`TrueType collection fonts are not yet supported by PDFsharp.`,请问你是怎么解决的?是要转换字体格式?

**Comment by HmgsLJ** [comment]
https://www.cnblogs.com/laikwan/p/18206787
看看这个，里面有个ChineseFontResolver？然后把字体路径指向本地？

**Comment by Varorbc** [comment]
@HmgsLJ 谢谢,我已经自己实现了,并解决了ttc转ttf的问题

**Comment by HmgsLJ** [comment]
ok




癸深
***@***.***
