### ISSUE TITLE
cannot open pdf created by PdfSharp

### ISSUE THREAD

**Issue by fishmanmisha** [empira/PDFsharp#117]
pdf contains images only

[PDFsharp.IssueSubmissionTemplate-master-fm.zip](https://github.com/empira/PDFsharp/files/15402874/PDFsharp.IssueSubmissionTemplate-master-fm.zip)

**Comment by ThomasHoevel** [comment]
Thanks for your feedback.
I can replicate the issue and it will be fixed with the final release PDFsharp 6.1.0, probably coming soon now.

**Comment by StLange** [comment]
Fixed in the release from yesterday.

**Comment by fishmanmisha** [comment]
when v6.1 final will be available on NuGet?

**Comment by ThomasHoevel** [comment]
Release date May 28, 2024.

**Comment by fishmanmisha** [comment]
The last PDFSharp on NuGet is from Tuesday, 30 April 2024 (30/04/2024), version 6.1.0-preview-3

**Comment by ThomasHoevel** [comment]
No, I see a newer version.
![image](https://github.com/empira/PDFsharp/assets/15982318/bbb9a29e-dec5-4b32-b0e3-558cc482d618)

**Comment by fishmanmisha** [comment]
Thanks, you right!
