### ISSUE TITLE
MigraDoc: LeftPadding seems to be negated when drawing Table

### ISSUE THREAD

**Issue by helluvamatt** [empira/PDFsharp#122]
There seems to be an issue with using `LeftPadding` on a `Table` or `Column` with MigraDoc. I am using the "Core" build.

## Expected Behavior

The generated PDF should contain a table with a single cell which spans the full width of the page (minus margins) and contains some centered text.

## Actual Behavior

The generated PDF contains a table with a single cell that is rendered off the left side of the page.

Example: [bug.pdf](https://github.com/user-attachments/files/15592740/bug.pdf)

## Steps to Reproduce the Behavior

Use the following code to generate a PDF which reproduces this bug. You may also need code to setup fonts and styles to use the fonts.

```csharp
Document document = new();

Section section = document.AddSection();
section.PageSetup.PageFormat = PageFormat.Letter;
section.PageSetup.LeftMargin = Unit.FromInch(0.5);
section.PageSetup.RightMargin = Unit.FromInch(0.5);
section.PageSetup.TopMargin = Unit.FromInch(0.5);
section.PageSetup.BottomMargin = Unit.FromInch(0.5);

Table table = section.AddTable();
Column column = table.AddColumn(Unit.FromInch(7.5)); // 8.5 - 0.5 - 0.5 (Letter size - left margin - right margin)
column.LeftPadding = Unit.FromInch(1);
column.RightPadding = Unit.FromInch(1);
Row row = table.AddRow();
row.TopPadding = 10; // pt
row.BottomPadding = 10; // pt
Cell cell = table[0, 0];
cell.Shading.Color = Colors.LightGray;
cell.Borders.Style = BorderStyle.Single;
cell.Borders.Color = Colors.Red;
cell.Format.Alignment = ParagraphAlignment.Center;
cell.AddParagraph("This text should be centered horizontally on the page.");

// Render document to PDF
PdfDocumentRenderer renderer = new()
{
    Document = document
};
renderer.RenderDocument();
renderer.PdfDocument.Save("path/to/bug.pdf");
```

**Comment by ThomasHoevel** [comment]
The behavior of MigraDoc tables is exactly as we see it with MS Word tables.

I admit the behavior of LeftPadding was counter-intuitive at first, but it is a feature, not a bug.

**Comment by helluvamatt** [comment]
Damn. I'm used to CSS where _every_ CSS framework/reset sets `box-sizing: border-box;` when the default is `content-box` which is this exact behavior. Nothing to see here, move along citizen.

**Comment by ThomasHoevel** [comment]
I'd like to mention that maybe the desired effect can also be achieved using a `Paragraph` with border and background color instead of using a table.
