### ISSUE TITLE
Query for PDFsharp v1.50 beta 5 (ECCN)

### ISSUE THREAD

**Issue by shq251** [empira/PDFsharp#125]
Hi PDFSharp-Team,

I am using the PDFSharp version 1.50 (beta 5) in my project. In my project, we used metadata functionality for update the pdf file metadata.
I have received the below queries from my client. 

1. What is the ECCN and CCATS number for PDFSharp (v1.5 beta 5).
2. Please tell me the encryption method and number of bits on PDF Sharp. Which the encryption algorithm, AES or RC4?
3. Please tell me about the basis for Standard Encryption like as FIPS numbers for PDFSharp (v1.5 beta 5).
4. Please let me know if I need to disclose the license of each open-source software.

Kindly provide the above details.

Thank you in advance,

**Comment by TH-Soft** [comment]
We can close here since this repo is for PDFsharp 6.x.

Question can also be found on the support forum:
https://forum.pdfsharp.net/viewtopic.php?p=14340#p14340

Repo for PDFsharp 1.5 can be found here:
https://github.com/empira/PDFsharp-1.5
