### ISSUE TITLE
PDFsharp fails to open pdfs.

### ISSUE THREAD

**Issue by KlaskSkovby** [empira/PDFsharp#13]
Here are two PDFs which fails to open with PDFsharp 

Fails in PdfTrailer
[Detaljer ARGO KOD rev.B.pdf](https://github.com/empira/PDFsharp/files/11471455/Detaljer.ARGO.KOD.rev.B.pdf)

Gets Unexpected EOF
[20-0193 - GR.10 BJÆLKER. ENDELIGE.pdf](https://github.com/empira/PDFsharp/files/11471458/20-0193.-.GR.10.BJAELKER.ENDELIGE.pdf)

code used to test this is from the sample collection.
works on other pdfs without issues

`            
            string filename1 = @"Detaljer ARGO KOD rev.B.pdf";
            string filename2 = @"20-0193 - GR.10 BJÆLKER. ENDELIGE.pdf";

            // Open the input files
            PdfDocument inputDocument1 = PdfReader.Open(filename1, PdfDocumentOpenMode.Import);
            PdfDocument inputDocument2 = PdfReader.Open(filename2, PdfDocumentOpenMode.Import);

            // Create the output document
            PdfDocument outputDocument = new PdfDocument();

            // Show consecutive pages facing. Requires Acrobat 5 or higher.
            outputDocument.PageLayout = PdfPageLayout.TwoColumnLeft;

            XFont font = new XFont("Verdana", 10, XFontStyle.Bold);
            XStringFormat format = new XStringFormat();
            format.Alignment = XStringAlignment.Center;
            format.LineAlignment = XLineAlignment.Far;
            XGraphics gfx;
            XRect box;
            int count = Math.Max(inputDocument1.PageCount, inputDocument2.PageCount);
            for (int idx = 0; idx < count; idx++)
            {
                // Get page from 1st document
                PdfPage page1 = inputDocument1.PageCount > idx ?
                  inputDocument1.Pages[idx] : new PdfPage();

                // Get page from 2nd document
                PdfPage page2 = inputDocument2.PageCount > idx ?
                  inputDocument2.Pages[idx] : new PdfPage();

                // Add both pages to the output document
                page1 = outputDocument.AddPage(page1);
                page2 = outputDocument.AddPage(page2);

                // Write document file name and page number on each page
                gfx = XGraphics.FromPdfPage(page1);
                box = page1.MediaBox.ToXRect();
                box.Inflate(0, -10);
                gfx.DrawString(String.Format("{0} • {1}", filename1, idx + 1),
                  font, XBrushes.Red, box, format);

                gfx = XGraphics.FromPdfPage(page2);
                box = page2.MediaBox.ToXRect();
                box.Inflate(0, -10);
                gfx.DrawString(String.Format("{0} • {1}", filename2, idx + 1),
                  font, XBrushes.Red, box, format);
            }

            // Save the document...
            const string filename = "CompareDocument1_tempfile.pdf";
            outputDocument.Save(filename);
`

**Comment by ThomasHoevel** [comment]
Using the latest internal builds, I had no problem opening filename2.
Opening filename1 fails because there are duplicate IDs. File can be opened after using "Save as" in Adobe Reader.

PDFsharp does not attempt to fix all issues with corrupt files.
