### ISSUE TITLE
Does anyone know how to remove image from a PDF?

### ISSUE THREAD

**Issue by Charltsing** [empira/PDFsharp#135]
[2.zip](https://github.com/user-attachments/files/16230591/2.zip)
[Removed-err.zip](https://github.com/user-attachments/files/16230752/Removed-err.zip)

![2](https://github.com/user-attachments/assets/9be83ebb-2655-4304-bb3a-14db8ebb74a6)

```
PdfDocument pdfDocument = PdfReader.Open("2.pdf", PdfDocumentOpenMode.Modify);
foreach (PdfPage page in pdfDocument.Pages)
{
    PdfResources resurce = page.Resources;
    PdfDictionary xobjects = (PdfDictionary)resurce.Elements["/XObject"];
    foreach (var xobject in xobjects.Elements)
    {
        if (xobject.Key == "\Im2") xobjects.Elements.Remove(xobject.Key);     
    }
}
pdfDocument.Save("2-new.pdf");
pdfDocument.Close();
```

PDF files that delete images in this way will report an error when opened

Does anyone know how to properly remove images from a PDF?

**Comment by ThomasHoevel** [comment]
You also have to remove all references to "\Im2" from the content stream.

Please use Discussions or the Forum for that sort of questions.

**Comment by Charltsing** [comment]
> You also have to remove all references to "\Im2" from the content stream.
> 
> Please use Discussions or the Forum for that sort of questions.

https://github.com/empira/PDFsharp/discussions/136
How to get the contents stream?

**Comment by phoeson** [comment]
What is the program of the screenshot to show the pdf file contents?

**Comment by phoeson** [comment]
> > You also have to remove all references to "\Im2" from the content stream.
> > Please use Discussions or the Forum for that sort of questions.
> 
> [#136](https://github.com/empira/PDFsharp/discussions/136) How to get the contents stream?

How to remove the references from the content stream?

**Comment by phoeson** [comment]
foreach (PdfPage page in doc.Pages)
                {
                    var resources = page.Resources;
                    PdfDictionary xobjects = resources.Elements["/XObject"] as PdfDictionary;
                    if (xobjects == null || !xobjects.Elements.ContainsKey("/img0"))
                    {
                        continue;
                    }

                    // 1) Remove the "/img0 Do" invocation(s) from the page content stream first,
                    //    otherwise the viewer executes a Do that points at a missing XObject and
                    //    reports "An error exists on this page".
                    CSequence sequence = ContentReader.ReadContent(page);
                    RemoveXObjectInvocation(sequence, "/img0");
                    page.Contents.ReplaceContent(sequence);

                    // 2) Now it is safe to drop the XObject definition itself.
                    xobjects.Elements.Remove("/img0");
                }


        /// <summary>
        /// Recursively removes every "<name> Do" operator that invokes the given XObject
        /// (e.g. "/img0") from a parsed content sequence, so the stream no longer references an
        /// XObject that is about to be deleted from the page resources.
        /// </summary>
        private static void RemoveXObjectInvocation(CSequence sequence, string xobjectName)
        {
            for (int i = sequence.Count - 1; i >= 0; i--)
            {
                CObject obj = sequence[i];
                if (obj is CSequence nested)
                {
                    RemoveXObjectInvocation(nested, xobjectName);
                }
                else if (obj is COperator op && op.Name == "Do"
                         && op.Operands.Count > 0
                         && op.Operands[0] is CName name
                         && name.Name == xobjectName)
                {
                    sequence.RemoveAt(i);
                }
            }
        }
