### ISSUE TITLE
When I reference PdfSharp, why is a directory named de created in the output directory?

### ISSUE THREAD

**Issue by Charltsing** [empira/PDFsharp#137]
![1](https://github.com/user-attachments/assets/2bc057b9-6eb9-4a9d-bf8e-aed632a78b44)
![2](https://github.com/user-attachments/assets/b54a5b66-c76e-4cc7-aa7e-fe9651c3fe37)

Windows10,  Simplified Chinese version

**Comment by ThomasHoevel** [comment]
This is not an issue. PDFsharp includes German error messages in the DE folder.

**Comment by Charltsing** [comment]
maybe it should be changed to en-US

**Comment by ThomasHoevel** [comment]
The EN-US error messages are included in the main folder.

**Comment by Charltsing** [comment]
If the DE folder is not necessary, would you like to remove it in future versions?

**Comment by ThomasHoevel** [comment]
"Not necessary" does not mean "not used".
You can leave the DE folder out when redistributing your application. For the time being, we include that folder with our German applications.

**Comment by StLange** [comment]
In the end, you're right. I have removed the resources and thus the directories. All texts are now only available in American English.

**Comment by Charltsing** [comment]
thanks a lot
