### ISSUE TITLE
Working with coordinates

### ISSUE THREAD

**Issue by nk-alex** [empira/PDFsharp#138]
My scenario: 
I receive a list of elements and I would like to create a Table element and place it on the Document using coordinates.

I would like to know if somehow I could create the table passing a coordinate of the document, let's just say (25, 34), and height and width . The columns would have to take the table space evenly.

I only found this [sample](https://forum.pdfsharp.net/viewtopic.php?p=9038), but it's using image instead:

**Comment by ThomasHoevel** [comment]
When you create a MigraDoc document, there are no pages and no coordinates.

Columns get the absolute width you assign to them.

Depending on your requirements, using `TextFrame` objects may be a solution. TextFrames do not break to the next page.

Closed because it is not an issue.
