### ISSUE TITLE
Image has no valid type error

### ISSUE THREAD

**Issue by amulya-pokala** [empira/PDFsharp#14]
I am using the pdfsharp-migradoc 6.0.0-preview-2 and facing the following problem

I have the image as a base64 string and I am using the following code to add it to the document.
```
private static void AddLabels(Document document, IList<string> images)
        {
            var section = document.LastSection;

            // Add an image
            for (int i = 0; i < images.Count; ++i)
            {
                if (i > 0)
                {
                    section.AddPageBreak();
                }
                var image = section.AddImage("base64:" + images[i]);
                image.LockAspectRatio = true;
                image.Height = "4in";
            }

        }
```
```
AddLabels(document, images);
 var renderer = new PdfDocumentRenderer
            {
                // Associate the MigraDoc document with a renderer.
                Document = document,
                PdfDocument = new PdfDocument()
            };
            renderer.RenderDocument();
using (var stream = new MemoryStream())
            {
                string filename = "C:\\HelloMigraDoc.pdf";
                renderer.PdfDocument.Save(filename);
            }
```
And this is the result I get.
![image](https://github.com/empira/PDFsharp/assets/14961791/f298b647-0b5d-45de-9fdc-ee720368ce06)

This code was working fine and was giving the image in the pdf with pdfsharp-migradoc (1.50)

Is there anything that I am missing here with the new version of pdfsharp-migradoc

**Comment by ThomasHoevel** [comment]
> Is there anything that I am missing here with the new version of pdfsharp-migradoc

Maybe yes. Did you switch from GDI or WPF build to the Core build? This would explain the issue.

**Comment by JunHaoShih** [comment]
So what should I do if I got this error on PDFsharp-MigraDoc 6.2.1?

**Comment by ThomasHoevel** [comment]
> So what should I do if I got this error on PDFsharp-MigraDoc 6.2.1?

If it worked with PDFsharp-MigraDoc 1.50, then switch to PDFsharp-MigraDoc-GDI 6.2.1.

**Comment by JunHaoShih** [comment]
@ThomasHoevel Thanks!
