### ISSUE TITLE
Incorrect parsing of REVERSE SOLIDUS in literal string

### ISSUE THREAD

**Issue by Greybird** [empira/PDFsharp#154]
# Reporting an Issue Here
When parsing some files, I noticed some Info Elements are showing incorrect values.
For example, for [this file](https://github.com/user-attachments/files/16672066/Cover-letter-4098208.pdf), the Producer tag:
* is shown by Acrobat as `C48x Series (PDF - 300X300 dpi)`.
![image](https://github.com/user-attachments/assets/932023fe-6e06-46b8-9795-3d5184ade466)
* is parsed by PDFSharp as `C48x Series (DF - 300X300 dpi)` (missing P)

## Expected Behavior
When parsing literal string, when a REVERSE SOLIDUS is encountered with an immediate following character not part of Table 3 of 7.3.4.2 paragraph of [ISO/DIS 32000-2](https://developer.adobe.com/document-services/docs/assets/5b15559b96303194340b99820d3a70fa/PDF_ISO_32000-2.pdf), the REVERSE SOLIDUS should be ignored, **but the following character should be kept**.

## Actual Behavior
When parsing literal string, when a REVERSE SOLIDUS is encountered with an immediate following character not part of Table 3 of 7.3.4.2 paragraph of ISO/DIS 32000-2, the REVERSE SOLIDUS is ignored, **as well as the following character**.

## Steps to Reproduce the Behavior

```
[Fact]
public void ReverseSolidus_with_invalid_following_character_should_be_ignored()
{
    using var doc = PdfReader.Open(@"Cover-letter-4098208.pdf");
    var producer = doc.Info.Producer;
    producer.Should().Be("C48x Series (PDF - 300X300 dpi)");
}
```
> Expected producer to be "C48x Series (PDF - 300X300 dpi)" with a length of 31, but "C48x Series (DF - 300X300 dpi)" has a length of 30, differs near "DF " (index 13).

The issue is most probably linked to an open question in the specification interpretation, as explained in [this comment of Lexer.cs](https://github.com/empira/PDFsharp/blob/5fbf6ed14740bc4e16786816882d32e43af3ff5d/src/foundation/src/PDFsharp/src/PdfSharp/Pdf.IO/Lexer.cs#L613C37-L623C38)

**Comment by ThomasHoevel** [comment]
Thanks for your feedback.

Issue should be resolved with PDFsharp 6.2.0 Preview 2.
