### ISSUE TITLE
Png Decode Error With BitsPerComponent==4

### ISSUE THREAD

**Issue by lld1995** [empira/PDFsharp#158]
Version:v6.2.0-preview-1

![image](https://github.com/user-attachments/assets/e0f8ae27-1a62-4cda-9649-c61069b3372e)

![image](https://github.com/user-attachments/assets/7e597ae2-f3e8-42dd-9aba-0de85b207b1d)

[tt18.pdf](https://github.com/user-attachments/files/16725410/tt18.pdf)

**Comment by lld1995** [comment]
It's a pixel data without header

**Comment by ThomasHoevel** [comment]
Since you closed this issue, I assume the PDF is corrupted and there is nothing to be done about this case.
