### ISSUE TITLE
MigraDoc: AddImage nolonger supports usage of memorystream

### ISSUE THREAD

**Issue by pascaltippelt** [empira/PDFsharp#16]
# Reporting an Issue Here
## Expected Behavior

Adding an image to a paragraph (eg a bitmap as supported) from a memorystream instead of a file-path should be supported again. 
(see: http://pdfsharp.net/wiki/MigraDoc_FilelessImages.ashx )

## Actual Behavior

![grafik](https://github.com/empira/PDFsharp/assets/2066297/45239dc7-f4ed-4839-84cd-a276e5930b6f)
(German for "Image not read")

## Steps to Reproduce the Behavior

As described in http://pdfsharp.net/wiki/MigraDoc_FilelessImages.ashx

**Comment by TH-Soft** [comment]
MigraDoc never supported images from MemoryStreams.
AddImage for BASE64-encoded images still works.
Please note that not all builds of MigraDoc (Core, GDI, WPF) support all image formats.

See also:
https://docs.pdfsharp.net/General/IssueReporting.html

**Comment by pascaltippelt** [comment]
I am sorry to have overread the IssueReporting artice + repo. 

The ZIP is attaced for issue in \src\Migradoc\src\IssueSubmission

[Issue.zip](https://github.com/empira/PDFsharp/files/11634855/Issue.zip)

The not loaded image is on the second page on the pdf:

[IssueTemplate-1748D98F5898417D8C161BF23CD645CE_tempfile.pdf](https://github.com/empira/PDFsharp/files/11634862/IssueTemplate-1748D98F5898417D8C161BF23CD645CE_tempfile.pdf)

**Comment by ThomasHoevel** [comment]
Thank you for supplying the image. Now I can replicate the problem.
There is a bug with the Core build - should be fixed with preview-3 coming this month or next month or so.

The image works with GDI build and WPF build. I don't know if these builds are an option for you.

**Comment by ThomasHoevel** [comment]
Preview 3 is now online and this bug should be fixed.

**Comment by pascaltippelt** [comment]
Thank you.

Is there any chance, you update the nuget Package? Currently nuget lists still previev-2 ( https://www.nuget.org/packages/PDFsharp-MigraDoc/6.0.0-preview-2 )

**Comment by TH-Soft** [comment]
The NuGet packages have been uploaded, but the Preview 2 packages are still there.

https://www.nuget.org/packages/PDFsharp-MigraDoc/6.0.0-preview-3

**Comment by pascaltippelt** [comment]
I am sorry - my fault!
