### ISSUE TITLE
MAUI Android: "Specified method is not supported." exception in PdfReader.Open()

### ISSUE THREAD

**Issue by schnuch** [empira/PDFsharp#17]
Hi and thanks for the project.

# Reporting an Issue Here

When I try to load a PDF on Android I get an exception (Specified method is not supported.) on PdfReader.Open().
I tried different PDF files in the Android Emulator and on a real device.
Opening, manipulating and saving works flawlessly on a MAUI Windows build.

The exception gets thrown in the following code in **Android.Runtime.InputStreamInvoker**, because `BaseFileChannel` is `null`:
```cs
public override long Length {
	get {
		if (BaseFileChannel != null)
			return BaseFileChannel.Size ();
		else
			throw new NotSupportedException ();
	}
}
```
This seems to be called from **PdfSharp.Pdf.IO.Lexer..ctor**.

Is this a bug in PDFsharp or MAUI?

## Expected Behavior
PDF gets loaded.

## Actual Behavior
NotSupportedException

## Steps to Reproduce the Behavior
I created a completely new MAUI project (with net6 and net7) and added PDFsharp (6.0.0-preview-2), a PDF file as a raw resource / MauiAsset and the following code right at the end of the example `OnCounterClicked()` function in MainPage.xaml.cs:

```cs
using Stream stream = await FileSystem.OpenAppPackageFileAsync("test.pdf");
PdfDocument doc;
try {
	doc = PdfReader.Open(stream);
} catch(Exception ex) {
	Debug.WriteLine($"ERROR: {ex.Message}");
	return;
}
Debug.Assert(doc != null && doc.Pages.Count > 0);
```

VS 2022 version 17.6.2

**Comment by ThomasHoevel** [comment]
There are different types of streams with different capabilities.

Does it work when you invoke PdfReader.Open with the filename, not the Stream?

**Comment by schnuch** [comment]
Further research revealed that the cause of this problem indeed lies within MAUI/Android as the length of the returned stream is unknown because of the way Android handles assets.
Saving the stream to a file and then using PdfReader.Open() with that file works, but the simplest workaround for me right now is to copy the stream to a MemoryStream:

```cs
using Stream stream = await FileSystem.OpenAppPackageFileAsync("test.pdf");
MemoryStream ms = new();
stream.CopyTo(ms);
PdfDocument doc = PdfReader.Open(ms);
```

Sorry for the false alarm.
