### ISSUE TITLE
ImageSelector hash ignores transparency mask

### ISSUE THREAD

**Issue by jellemuylle** [empira/PDFsharp#175]
example attached. bug only shows in plain PDFsharp (not in gdi or wpf versions)

if you include 2 transparent PNG images that have identical bitmap data but differ only in the transparency mask data then DrawImage thinks they are the same. only the first image is included in the image table and the second is a repeat.

the root cause is that the ImageSelector that powers the image table uses MD5 hashes that are based on the bitmap data only and not on the transparency mask data.
(https://github.com/empira/PDFsharp/blob/master/src/foundation/src/PDFsharp/src/PdfSharp/Pdf.Advanced/PdfImageTable.cs line 80)

[Issue.zip](https://github.com/user-attachments/files/17153823/Issue.zip)

**Comment by ThomasHoevel** [comment]
Known issue, see #127 
Fixed with current internal builds, should be fixed with a forthcoming preview build.

**Comment by ThomasHoevel** [comment]
Issue should be resolved with PDFsharp 6.2.0 Preview 2.
