### ISSUE TITLE
Ximage FromStream Exception

### ISSUE THREAD

**Issue by LordGalahad** [empira/PDFsharp#18]
Good Day!

I am always getting a "memorystream's internal buffer cannot be accessed".

What I do is I get a Base64String representation of an image then I convert it into a byte array. Then I put the byte array into a memory stream. Then I feed it into XImage and get an exception

![image](https://github.com/empira/PDFsharp/assets/61867299/0b38e567-2f1d-4569-8775-6dc07b8ff441)

I've been switching between this and the PDFSharpCore implementation. PDFSharpCore uses a different parameter like XImage.FromStream(() => ms) instead and it seems to be working on their side.

**Comment by TH-Soft** [comment]
You have to make the buffer accessible. Use a `MemoryStream` that is publicly visible.

`public MemoryStream (byte[] buffer, int index, int count, bool writable, bool publiclyVisible);`
