### ISSUE TITLE
XGraphics.DrawImage() PNG image without transparency

### ISSUE THREAD

**Issue by NintendoPlayer** [empira/PDFsharp#187]
Hi.

I upgraded my project to NET.8 and installed 6.2.0-preview-1.  Besides some changes, everything works fine.  I'm having a weird issue with this version.

I load a png image from a database, then I save it to a memorystream.  I save it to an XImage object and then draw it to the last page of the pdf.

With the old 1.51 library, the png retained the transparency.  Now the png draws with white background thus hidding the objects behind it.

**Comment by ThomasHoevel** [comment]
Would be good to know which version of PDFsharp you are using and would be good to have the PNG file for testing.

https://docs.pdfsharp.net/General/Issue-Reporting.html

**Comment by NintendoPlayer** [comment]
Hi!  Version is 6.2.0-preview 1, is on the first message  About the png file is a signature so I will try with another file to see if the issue persist.

**Comment by ThomasHoevel** [comment]
Would be good to know which version of PDFsharp you are using: Core, GDI, or WPF.
But that only matters if we also get the PNG file.

**Comment by waleswood** [comment]
PDFsharp6.1.1
 .net6
I had the same problem

**Comment by ThomasHoevel** [comment]
> PDFsharp6.1.1 .net6 I had the same problem

> But that only matters if we also get the PNG file.

**Comment by waleswood** [comment]
[test.pdf](https://github.com/user-attachments/files/17729035/test.pdf)
You can use the attached test.pdf
Try inserting a transparent png image into this pdf

**Comment by ThomasHoevel** [comment]
I thought there was a problem with certain PNG files. Now it looks as if there is a problem with certain PDF files.
We'd like to have precise repro steps.
See also:
https://docs.pdfsharp.net/General/Issue-Reporting.html

**Comment by ThomasHoevel** [comment]
Update: The PDF file is marked "1.3".
At least 1.4 is required for full support of transparency.
No alpha transparency is used if the PDF file targets Acrobat Reader 4.0 or earlier.
Then it would be no bug.

**Comment by waleswood** [comment]
Can PDFsharp automatically change 1.3 to 1.4?

**Comment by ThomasHoevel** [comment]
> With the old 1.51 library, the png retained the transparency. Now the png draws with white background thus hidding the objects behind it.

There is no code that show a regression of PDFsharp 6.x versus PDFsharp 1.51. Issue closed.

**Comment by waleswood** [comment]
I tried all versions of PDFsharp 6.x

**Comment by NintendoPlayer** [comment]
I don't know if there was something changed with old libraries or not, but I started having this issue with 6.x

**Comment by waleswood** [comment]
I switched to PdfSharpCore

**Comment by ThomasHoevel** [comment]
> Can PDFsharp automatically change 1.3 to 1.4?

You can set the version you need.

` if (doc.Version < 14)
     doc.Version = 14;`
     
 Here, *doc* is your instance of *PdfDocument*.

**Comment by ThomasHoevel** [comment]
> I don't know if there was something changed with old libraries or not, but I started having this issue with 6.x

For us it would be good to have a PDF, a PNG, and some code to replicate the issue.

Are you using PDFsharp-GDI?

Transparency works for our PNG sample images.

**Comment by waleswood** [comment]
``` C#
if (doc.Version < 14) doc.Version = 14;
```
Solved my problem,I really appreciate it.‌ 

no, I used PDFsharp

**Comment by NintendoPlayer** [comment]
Same here, it solved my issues.
