### ISSUE TITLE
Suggestion: PdfDocumentRenderer.RenderDocument() should support cancel/stop

### ISSUE THREAD

**Issue by heku** [empira/PDFsharp#19]
Hi,

Because when creating a large PDF, the `PdfDocumentRenderer.RenderDocument()` may take several minutes to execute, it's better to add a API to allow cancelling/stopping it.

**Comment by TH-Soft** [comment]
It is possible to render documents page by page. If you do it this way, you can stop or cancel as well.

**Comment by heku** [comment]
Thanks, I will have a try.

**Comment by heku** [comment]
Hi @TH-Soft , I tried your suggestion, yes I can render documents page by page, but before that, the call to `PrepareRenderPages()` still take time to execute, is it possible to provide a method or parameter to allow user cancel it?

**Comment by TH-Soft** [comment]
There is a callback that allows you to display the progress of the preparation. I don't know how to stop the preparation from within the callback. Not sure if throwing an exception is enough to stop preparation.
Another approach: create a thread to do the preparation and kill the thread and the document when user wants to cancel rendering.

Link to sample code in the support forum (shows progress, but does not yet support cancellation):
https://forum.pdfsharp.net/viewtopic.php?f=8&t=3172

**Comment by heku** [comment]
Yes, wrap a thread is my current workaround, but it is better to add a method or parameter to make it cancelable, because thread.abort is not recommend as it's _unsafe_, and recent .net core even drop support for it.

My proposal is, add a new method `PrepareRenderPages(CancellationToken token)`, and check the token inside via `token.ThrowIfCancellationRequested()`  is enough I think.

**Comment by ThomasHoevel** [comment]
I tested it: an exception thrown in `PrepareDocumentProgress` stops the preparation progress.
Thus preparation can easily be cancelled by throwing an exception.
Rendering can easily be stopped if you render page by page.

If you want to use a `CancellationToken`, just check it inside the callback and in the loop that renders the document.

**Comment by heku** [comment]
it works. thank you.
