### ISSUE TITLE
PDFSharp 6.2 preview.1 multiple digital signatures

### ISSUE THREAD

**Issue by Havunen** [empira/PDFsharp#192]
Hi,

I am trying to implement multiple digital signatures to existing pdf documents using PDFSharpCore 6.2preview.

I believe there is bug in digital signing. 

After digitally signing the same document multiple times, only the latest digital signature byte range matches.

Steps to reproduce:
Have a pdf document, for example sample.pdf https://pdfobject.com/pdf/sample.pdf
Sign it once with certificate.
Inspect the document with notepad++
![image](https://github.com/user-attachments/assets/56e3510c-41dc-4c97-b927-a0f267d9584e)
byterange of the signature matches as expected.
Sign the already signed document again.
now the first signature byterange is pointing out of bounds of the signature?
![image](https://github.com/user-attachments/assets/bf06350e-7ea3-4b93-960b-0d8b49db6cc1)

**Comment by ThomasHoevel** [comment]
This is the PDFsharp project, not the PdfSharpCore project.

When using PDFsharp, you currently have to include the PR for incremental updates. This is by design.

**Comment by Havunen** [comment]
Is there some package available in Nuget.org where that change is included?

**Comment by Havunen** [comment]
another solution what comes to mind, could be to pre-allocate multiple signature blocks to the document and then later filling those? Is that supported in PDFSharp?

**Comment by ThomasHoevel** [comment]
We do not yet have a solution for multiple signatures.
