### ISSUE TITLE
"Object already in table."

### ISSUE THREAD

**Issue by tfouto** [empira/PDFsharp#193]
I get this error, 

"Object already in table."

"   at PdfSharp.Pdf.Advanced.PdfCrossReferenceTable.Add(PdfObject value)\r\n   at PdfSharp.Pdf.PdfDictionary.DictionaryElements.GetValue(String key, VCF options)\r\n   at PdfSharp.Pdf.Advanced.PdfTrailer.get_SecurityHandler()\r\n   at PdfSharp.Pdf.PdfDocument.get_SecurityHandler()\r\n   at PDFAPI.Program.PdfIsProtectedWithLimitedPermissions2(Byte[] documentContent) in 

when accessing this code:
canPrint = securitySettings.PermitPrint;

**Comment by ThomasHoevel** [comment]
Most likely a duplicate:
https://forum.pdfsharp.net/viewtopic.php?p=14548#p14548

Should be fixed with the next preview.

Would be good to have a PDF to confirm our changes.

**Comment by tfouto** [comment]
Ther error only occurs in PdfDocumentOpenMode.ReadOnly.

If I use
var inputDocument = PdfReader.Open(stream, PdfDocumentOpenMode.Modify);

it doesn't occur.

I have a document but its has confidential information. Business info, so I can't apply. But I can test it if you send me a new dll.

**Comment by jcipsen** [comment]
I'm encountering the same error : Object already in table  when attempting to open the document in PdfDocumentOpenMode.Import mode.

However, when I attempted the suggested workaround of opening the document in PdfDocumentOpenMode.Modify mode—despite not needing to make modifications—it still resulted in an error, as detailed below.

The document is not password protected and opens in Adobe reader without any issues.

PdfSharp.Pdf.IO.PdfReaderException
  HResult=0x80131500
  Message=T**o modify the document the owner password is required**
  Source=PdfSharp
  StackTrace:
   at PdfSharp.Pdf.IO.PdfReader.OpenFromStream(Stream stream, String password, PdfDocumentOpenMode openMode, PdfPasswordProvider passwordProvider, PdfReaderOptions options)
   at PdfSharp.Pdf.IO.PdfReader.OpenFromFile(String path, String password, PdfDocumentOpenMode openMode, PdfPasswordProvider passwordProvider)
   at PdfSharp.Pdf.IO.PdfReader.Open(String path, PdfDocumentOpenMode openMode, PdfReaderOptions options) 

  This exception was originally thrown at this call stack:
    [External Code]

**Comment by ThomasHoevel** [comment]
Issue should be resolved with PDFsharp 6.2.0 Preview 2.
