### ISSUE TITLE
Error Opening PDF file.

### ISSUE THREAD

**Issue by tfouto** [empira/PDFsharp#199]
{"Unexpected character '0xó' in PDF stream. The file may be corrupted. If you think this is a bug in PDFsharp, please send us your PDF file (issues (at) pdfsharp.net).\n+áQ⟬0C⟭ãíß)3〈VT〉\u008dµ\u008d\u0085Ö\"chÌ¬Ô\u0096⟬0C⟭+I‼óu〈HT〉⟬1C⟭§Ó7øeðë9n^\\\u009e\u0085£gÍó_§ñ¨\r\nPosition marked with ‼ is 151060"}

The pdf is perfectly fine. I can open it fine. Also PdfPig, can open the file, and process it.

**Comment by ThomasHoevel** [comment]
Where's the file?
