### ISSUE TITLE
Regression: No appropriate font found for family name "Segoe UI".

### ISSUE THREAD

**Issue by danielchalmers** [empira/PDFsharp#20]
## Expected Behavior

No error like in 1.51.5185-beta.

## Actual Behavior

```
 Message: 
System.InvalidOperationException : No appropriate font found for family name "Segoe UI".

  Stack Trace: 
XGlyphTypeface.GetOrCreateFrom(String familyName, FontResolvingOptions fontResolvingOptions)
XFont.Initialize()
XFont.ctor(String familyName, Double emSize, XFontStyleEx style, XPdfFontOptions pdfOptions)
XFont.ctor(String familyName, Double emSize, XFontStyleEx style)
FontHandler.FontToXFont(Font font)
ParagraphRenderer.get_CurrentFont()
ParagraphRenderer.CalcCurrentVerticalInfo()
ParagraphRenderer.InitFormat(Area area, FormatInfo previousFormatInfo)
ParagraphRenderer.Format(Area area, FormatInfo previousFormatInfo)
TopDownFormatter.FormatOnAreas(XGraphics gfx, Boolean topLevel)
<6 more frames...>
DocumentRenderer.PrepareDocument()
PdfDocumentRenderer.PrepareDocumentRenderer(Boolean prepareCompletely)
PdfDocumentRenderer.PrepareRenderPages()
PdfDocumentRenderer.RenderDocument()

```

## Steps to Reproduce the Behavior

```cs
        var style = document.Styles[StyleNames.Normal];
        style.Font.Name = "Segoe UI";
        style.Font.Size = 10;
```

**Comment by ThomasHoevel** [comment]
Make sure you are using the GDI or WPF package.
When using the "Core" package, make sure you set a `FontResolver` that supports all the fonts you need.

See also:
https://docs.pdfsharp.net/General/History.html

**Comment by danielchalmers** [comment]
@ThomasHoevel My project targets plain .NET 8, but the GDI package requires a `-windows` target which the base package does not. This forces me to stay on 1.51

**Comment by ThomasHoevel** [comment]
> @ThomasHoevel My project targets plain .NET 8, but the GDI package requires a `-windows` target which the base package does not. This forces me to stay on 1.51

Fascinating.
PDFsharp 1.51 depends on Windows, but is OK for you. How can it be?
The Core build of PDFsharp 6.0.0 does not require "-windows", but is not OK for you?

If you stick with version 1.51, test your application early under MacOS and Linux.
IMHO better use PDFsharp 6.0.0 Core build and register a FontResolver, that's all it takes.

**Comment by danielchalmers** [comment]
@ThomasHoevel Thank you, I'll look into that
