### ISSUE TITLE
PDFSharp support for Linux

### ISSUE THREAD

**Issue by Abhijeetsinghjat** [empira/PDFsharp#204]
Does pdfhsarp provides support for Linux?

**Comment by ThomasHoevel** [comment]
PDFsharp can be used under Linux.

**Comment by Abhijeetsinghjat** [comment]
but it has some GDI+ dependencies will it work with linux?
@ThomasHoevel

**Comment by ThomasHoevel** [comment]
Not all builds depend on GDI+.
https://docs.pdfsharp.net/General/Overview/NuGet-Packages.html
