### ISSUE TITLE
PdfSharp and flexbox(css level3)

### ISSUE THREAD

**Issue by blohin27** [empira/PDFsharp#22]
Greetings! When using this library, I get the following error. I understand that PDFsharp does not support css higher than level2 and html higher than 4.01 . Do I understand correctly that versions higher are not supported by this program or do I need to upgrade to a later version? I want to use a flexbox-based build, but I get an error, Please help me

**Comment by ThomasHoevel** [comment]
Probably wrong forum: PDFsharp does not support any HTML and it does not support any CSS.
Questions about the HTML Renderer library should be asked on their fora.
