### ISSUE TITLE
6.0.0-preview-3 font colour always Black

### ISSUE THREAD

**Issue by ReviveDigitalTeam** [empira/PDFsharp#25]
Hey guys, we're very happy with the new version - Thank you for continuing to support this great PDF library!

We have been testing 6.0.0 on windows and ubuntu and it works great.

The only trouble we have encountered is we have not been able to adjust the Font colours on the rendered PDF from the black default.
This is on 6.0.0-preview-3 and using the NewFontResolver.

# Reporting an Issue Here
## Expected Behavior
Font colour changes to yellow or green.

## Actual Behavior
Font colour stays **black.**

## Steps to Reproduce the Behavior
```csharp
private const string VerdanaFontName = "Verdana";

private static readonly Font _greenFont = new() {
    Name = VerdanaFontName,
    Color = _green
};

public class VerdanaFontResolver : NewFontResolver {
    public byte[] GetFont(string faceName) {
        using var data = GeneralExtensions.GetEmbeddedStream(faceName, typeof(PdfMaker).Assembly);
        return data.AsByteArray();
    }
    public FontResolverInfo ResolveTypeface(string familyName, bool isBold, bool isItalic) {
        if (familyName == VerdanaFontName) {
            return new FontResolverInfo(VerdanaFontName);
        }
        throw new InvalidOperationException($"Font '{familyName}' is not supported.");
    }
}

var deetsPara = deetsFrame.AddParagraph();
deetsPara.AddFormattedText("Email Address\t\t", _greenFont);
var banner1 = section.AddA4TextBox(6.7, 1.75, 4);
banner1.AddParagraph().AddFormattedText("Total Due", _greenFont);

// RENDER
```

Is there a new way to set Font colours?

**Comment by ThomasHoevel** [comment]
Did this code work with earlier versions?

This is how you usually set the color of formatted text:
```
var formattedText = paragraph.AddFormattedText("color ");
formattedText.Color = Colors.Firebrick;

```

See also:
https://docs.pdfsharp.net/General/IssueReporting.html

**Comment by ReviveDigitalTeam** [comment]
Thank you! Setting the Color on the formattedText object after adding it works as I expect. 😁

The way I was doing it before, by passing a Font (with color already set) into the AddFormattedText method was working for me on version `1.51.5186-beta`.

**Comment by ThomasHoevel** [comment]
I fixed the bug in our internal repository. Will be fixed with the next release ("preview 4" or whatever name it will have).
Thanks for the feedback.
