### ISSUE TITLE
Borders serializer crashes

### ISSUE THREAD

**Issue by MrMorag** [empira/PDFsharp#28]
Namespace: MigraDoc.DocumentObjectModel
Class: Borders
Method: internal void Serialize(Serializer serializer, Borders? refBorders)

DiagonalDown is checked for null, but DiagonalUp is used then, which leads to a null ref exception:

internal void Serialize(Serializer serializer, Borders? refBorders)
{
...
if (!Values.**DiagonalDown**.IsValueNullOrEmpty())
{
		Values.**DiagonalUp**!.Serialize(serializer, "DiagonalDown", null);
}
if (!Values.DiagonalUp.IsValueNullOrEmpty())
{
		Values.DiagonalUp!.Serialize(serializer, "DiagonalUp", null);
}

**Comment by ThomasHoevel** [comment]
Do you have code that actually leads to a crash?
Just asking...
Yes, code looks wrong, but I guess it never gets executed.
Thanks for the feedback. Gonna fix it with the next release.

**Comment by MrMorag** [comment]
Yes, in our project it crashes exactly at this line if "DdlWriter.WriteToString(document)" is called for a preview.
It's a simple PDF with a table and borders. The creation of the PDF with the same data worked with 1.32 and the 1.5 versions

![image](https://github.com/empira/PDFsharp/assets/143007080/e6665fc1-29fd-432b-8c55-24bc6f94f152)

**Comment by MrMorag** [comment]
Meanwhile I figured out how to reproduce, add a table and set only:
table.Borders.DiagonalDown.Visible = false;

**Comment by ThomasHoevel** [comment]
Meanwhile I fixed it in our internal code. Thanks again for the feedback.
Setting DiagonalDown has no effect AFAIK - except for the crash in the Serializer.
