### ISSUE TITLE
'page.AddDocumentLink’ The selected area is incorrect

### ISSUE THREAD

**Issue by soul-soft** [empira/PDFsharp#30]
## Code

The selected areas of these two functions are incorrect, it seems that they are mirror symmetric
``` C#
var pdf = new PdfDocument();
var page = pdf.AddPage();
page.AddDocumentLink(new PdfRectangle(new XRect(0, 0, page.Width, 40)), 2);

var graphics = XGraphics.FromPdfPage(page);
graphics.DrawRectangle(XBrushes.Black, new XRect(0, 0, page.Width, 40));
pdf.Save("D:\\test2.pdf");
```

**Comment by ThomasHoevel** [comment]
From the source code documentation:
```
/// <summary>
/// Adds an internal document link.
/// </summary>
/// <param name="rect">The link area in default page coordinates.</param>
/// <param name="destinationName">The Named Destination's name.</param>
public PdfLinkAnnotation AddDocumentLink(PdfRectangle rect, string destinationName)
```

Conversion:

`rect = gfx.Transformer.WorldToDefaultPage(new XRect(new XPoint(100, 400), new XSize(350, 150)));`

**Comment by soul-soft** [comment]
> 从源代码文档中：
> 
> ```
> /// <summary>
> /// Adds an internal document link.
> /// </summary>
> /// <param name="rect">The link area in default page coordinates.</param>
> /// <param name="destinationName">The Named Destination's name.</param>
> public PdfLinkAnnotation AddDocumentLink(PdfRectangle rect, string destinationName)
> ```
> 
> 转换：
> 
> `rect = gfx.Transformer.WorldToDefaultPage(new XRect(new XPoint(100, 400), new XSize(350, 150)));`

nice!!!
