### ISSUE TITLE
Struggling with installing and use the package

### ISSUE THREAD

**Issue by Bilboramix** [empira/PDFsharp#31]
Hello there, i'm using .NET 6 and wpf 6.0.20 and i'm struggling with installing the package through nuget manager :
![image](https://github.com/empira/PDFsharp/assets/91626615/fc2828c5-ec72-40c2-97c0-5fd6abcc5cf1)
And when i try to use it i've got errors like this one :
```
System.NotSupportedException : 'No data is available for encoding 1252. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.'
```
The lines that are throwing are these one :
```c#
XGraphics gfx = XGraphics.FromPdfPage(pdfPage);
gfx.DrawString("Test", new XFont("Arial", 20, XFontStyle.Bold), XBrushes.Black, new XPoint(100, 50));
```

Is the version on the nuget manager outdated ? So should i build localy the package with the "6.0.0-preview-3" provided in the release tab here ? I never installed manualy a package and i'm a bit lost...

Also the doc says that this version is for testing purposes and that i should use "core build" but where can i find it ?

Regards, Bill.

**Comment by Bilboramix** [comment]
Installing through nuget CLI fixed this.

**Comment by ThomasHoevel** [comment]
The NuGet Manager will show all packages when you activate the "prerelease" option in the search filter.
PDFsharp 1.5 was developed for .NET 3.5 and when used with .NET 6, the problem with codepage 1252 will occur.
PDFsharp 6.0 should be used with .NET 6.

**Comment by Bilboramix** [comment]
Oh okay I did not noticed the checkbox at all...
Everything is working now, thanks a lot for your work ❤️
