### ISSUE TITLE
Dot in AcroFormField Name (Textfield) freaks field

### ISSUE THREAD

**Issue by PlPt-ads-tec** [empira/PDFsharp#34]
Hi,

if a have a Acro Form named for example "function_A_DoSth(mytext.txt)", PdfSharp splitx textfield on "dot" so in AcroForm Names i only can see "function_A_DoSth(mytext". I tried to debug but I dont find why this happens.
Do you have an Idea?

**Comment by packdat** [comment]
This is by convention as the PERIOD character is used for organizing fields into a field-hierarchy.
The [Pdf-Reference](https://opensource.adobe.com/dc-acrobat-sdk-docs/pdfstandards/PDF32000_2008.pdf) states in chapter 12.7.3.2:

> For a field that is the child of another field, the fully qualified name shall be formed by appending the child field’s partial 
name to the parent’s fully qualified name, separated by a PERIOD (2Eh) as shown:
parent’s_full_name.child’s_partial_name

And
> Because the PERIOD is used as a separator for fully qualified names, a partial name shall not contain a PERIOD character

In short, a PERIOD character (".") is not permitted in a field-name.
I'd suggest replacing the "." with something else.

**Comment by PlPt-ads-tec** [comment]
Thanks for the answer
