### ISSUE TITLE
SpaceBefore property value ignored in first paragraph

### ISSUE THREAD

**Issue by kobruleht** [empira/PDFsharp#39]
[spacebeforeignored.pdf](https://github.com/empira/PDFsharp/files/12905771/spacebeforeignored.pdf)
## Expected Behavior

Text should appear 20 cm below in page

## Actual Behavior

Text appears immediately at start of page  (see attached pdf file)

## Steps to Reproduce the Behavior

Run attached solution

Code:

```
        static Document CreateDocument()
        {
            var document = new Document { };
            var section = document.AddSection();
            section.PageSetup.TopMargin = 0;
            var par = section.AddParagraph("test");
            par.Format.SpaceBefore = "20cm";
            return document;
        }

```

[SpaceBeforePropertyValueIgnoredForFirstParagraph.zip](https://github.com/empira/PDFsharp/files/12905762/SpaceBeforePropertyValueIgnoredForFirstParagraph.zip)

[spacebeforeignored.pdf](https://github.com/empira/PDFsharp/files/12905776/spacebeforeignored.pdf)

**Comment by TH-Soft** [comment]
SpaceBefore is ignored for the first paragraph on a page. It's a feature, not a bug.
You can add a dummy paragraph to make SpaceBefore at the start of a new section.
