### ISSUE TITLE
Efficiently Merging multiple PDFs

### ISSUE THREAD

**Issue by jimbuck** [empira/PDFsharp#4]
I trying to implement a method to merge multiple PDFs together. Is there any best approach for handling this? I currently have something like this:

```csharp
using PdfDocument outputPdf = new PdfDocument();
foreach (var docId in documentIds)
{
    Stream incomingPdfFileStream = await _docService.DownloadDocument(docId);

    var sourcePdf = PdfReader.Open(incomingPdfFileStream, PdfDocumentOpenMode.Import);
    for (int i = 0; i < sourcePdf.PageCount; i++) {
        outputPdf.AddPage(sourcePdf.Pages[i]);
    }
}

Stream completePdfFileStream = new MemoryStream();
outputPdf.Save(completePdfFileStream);
return completePdfFileStream;
```

Any thoughts or recommendations is greatly appreciated!

**Comment by ThomasHoevel** [comment]
Please check these two samples:
https://pdfsharp.net/wiki/CombineDocuments-sample.ashx
https://pdfsharp.net/wiki/ConcatenateDocuments-sample.ashx
