### ISSUE TITLE
Footer overlap using negative SpaceBefore and minimum line height

### ISSUE THREAD

**Issue by kobruleht** [empira/PDFsharp#40]
[FooterOverlapswithpagecontent.zip](https://github.com/empira/PDFsharp/files/12908746/FooterOverlapswithpagecontent.zip)
## Expected Behavior

Footer text should not overlap with page content

## Actual Behavior

Footer text overlaps with page content

[footeroverlapswithpagefontents.pdf](https://github.com/empira/PDFsharp/files/12908745/footeroverlapswithpagefontents.pdf)

## Steps to Reproduce the Behavior

Run attached solution.

Code:

```
        static Document CreateDocument()
        {
            var document = new Document { };
            var Section = document.AddSection();
            Section.PageSetup.PageWidth = "210mm";
            Section.PageSetup.PageHeight = "297mm";
            Section.PageSetup.TopMargin = 0;
            Section.PageSetup.BottomMargin = Unit.FromCentimeter(2);
            for (int i = 0; i < 77; i++)
            {
                var par = Section.AddParagraph("paragraph " + i);
                par.Format.SpaceBefore = Unit.FromCentimeter(-0.5);
                par.Format.LineSpacingRule = LineSpacingRule.Exactly;
                par.Format.LineSpacing = "1cm";
            }
            var par1 = Section.Footers.Primary.AddParagraph("Footer overlaps");
            par1.Format.SpaceBefore = Unit.FromCentimeter(1);
            return document;
        }

```

**Comment by TH-Soft** [comment]
User code must ensure that document body does not overlap with header area or footer area.  
This is by design.

**Comment by kobruleht** [comment]
Code sets  bottom margin to 2 cm. Body does not overlap with footer. MigraDoc places footer pararagph in wrong position, into body area.

**Comment by TH-Soft** [comment]
Do you also get the overlap if you remove the line `par1.Format.SpaceBefore = Unit.FromCentimeter(1);`?

Setting a `SpaceBefore` of 1 cm in the footer does not make sense if the footer area is only 0.75 cm.
