### ISSUE TITLE
PDFsharp seems to be incompatible with .NET 6

### ISSUE THREAD

**Issue by stestp** [empira/PDFsharp#50]
PDFsharp seems to be incompatible with .NET 6

On the page https://docs.pdfsharp.net/General/Overview/Port-to-v6.0.html you can see that PDFSharp supports .NET 6, but there is the following warning:

`Project.csproj: [NU1701] Package 'PDFsharp 1.50.5147' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework 'net6.0-windows7.0'. This package may not be fully compatible with your project.`

Project.csproj has target framework net6.0-windows.

**Comment by TH-Soft** [comment]
Version 6.0.0 supports .NET 6.
Version 1.50 does not.
Get the correct version.
