### ISSUE TITLE
Encryption seems to break images that use indexed color

### ISSUE THREAD

**Issue by chrishaug** [empira/PDFsharp#54]
I have a PDF with an indexed color image of the company logo on every page. See attached for a similar document using an indexed version of the PDFsharp logo and which reproduces the issue ([indexed-color-encryption.zip](https://github.com/empira/PDFsharp/files/13341967/indexed-color-encryption.zip)). The original logo, without converting to indexed color, does not cause any issues.

Using PDFsharp (Core) 6.0, I set an owner password:

```csharp
public void ProcessFile(Stream inStream, Stream outStream) {
  var pdfDoc = PdfReader.Open(inStream);
  pdfDoc.SecuritySettings.OwnerPassword = "password";      
  pdfDoc.Save(outStream);
  pdfDoc.Close();
}
```

When opening the result, Acrobat reports that "An error exists on the page. Acrobat may not display the page correctly". `pdfimages` says there's something wrong with the palette:

```
$ pdfimages -list pdfsharplogo-indexed-output.pdf
Syntax Warning: Bad Indexed color space (lookup table string too short)
Syntax Error (101): Bad image parameters
page   num  type   width height color comp bpc  enc interp  object ID x-ppi y-ppi size ratio
--------------------------------------------------------------------------------------------
```

Under some encryption settings other than the default, Acrobat will actually render the image without any errors, but with the wrong colors. I've tested some other PDF readers and they sometimes render the PDF when Acrobat won't, but never with the right colors.

One thing I noticed is that the palette is *not* encrypted in the file (it's identical in the input and output files):

```
7 0 obj
[
/Indexed/DeviceRGB 255<000000FFFFFFFBD4DAFBDDE1FAE3E6FDE6E...>
]
endobj
```

However, I have done the same operation with other libraries (iText, IronPdf), and there the palette *does* seem to be encrypted, and there is no issue reading the file after. Is it possible that readers expect the palette to be encrypted and, when it isn't, end up trying to decrypt it and then use some nonsensical data as the palette?

Thanks in advance for any insights.

**Comment by ThomasHoevel** [comment]
Thanks for the feedback. I close here as we still have another encryption-related issue to deal with.
https://github.com/empira/PDFsharp/issues/51#issue-1972949346

**Comment by martinossendorf** [comment]
PDFsharp Version 6.1.0-preview-1 is now able to save the mentioned PDF file encrypted without breaking the image. The palette indeed has to be encrypted. The palette is saved as a hex string, which wrongly were not saved encrypted in PDFsharp.
Thanks for reporting the issue!
