### ISSUE TITLE
 Project cannot be compiled

### ISSUE THREAD

**Issue by HmgsLJ** [empira/PDFsharp#55]
If you think there is a bug in PDFsharp then please use the IssueSubmissionTemplate to make the issue replicable.  
https://docs.pdfsharp.net/General/IssueReporting.html

Thanks.

# Resources

The official project web site:  
https://docs.pdfsharp.net/

The official peer-to-peer support forum:  
http://forum.pdfsharp.net/

# Reporting an Issue Here

Hello，First of all, thanks for providing such a good class library.
But,【PdfSharp 6.0.0】Source Code Suspected lack of resource files caused the project to fail compilation.
Can you help me take a look?

**Comment by ThomasHoevel** [comment]
First step: Read the Readme and download the assets.
