### ISSUE TITLE
PdfSharp-Migradoc-GDI 6.0.0 with .net 8.0?

### ISSUE THREAD

**Issue by MarianoJP** [empira/PDFsharp#57]
Will you release a Nuget Package that works with .net 8.0. The current version 6.0.0 does not work with .net 8.0. In my project I am using .net core 8.0 due to components that require it.

**Comment by ThomasHoevel** [comment]
How do you define "does not work"?

The source code 6.0.0 can be compiled against .NET 8 and works fine as far as we tested it.

**Comment by MarianoJP** [comment]
My apologies. I am using the Nuget Package in Visual Studio and when I attempt to load it, it tells me that it cannot be used with .net 8.0.

Error	NU1202	Package PDFsharp-MigraDoc-GDI 6.0.0 is not compatible with net8.0 (.NETCoreApp,Version=v8.0). Package PDFsharp-MigraDoc-GDI 6.0.0 supports: net6.0-windows7.0 (.NETCoreApp,Version=v6.0)	

I can download the code and use it as a reference. 

Thanks.

P.D. I have modified from the older 1.50 version samples a function that will create an image of the first page of the pdf to use as a thumbnail/preview of the document that will be stored in my Blazor app. Below is the function.

`public static Image CreatePerview(PdfDocumentRenderer pdfr)
{
	PageInfo pageInfo = pdfr.DocumentRenderer.FormattedDocument.GetPageInfo(1);
	PdfDocument pdfDoc = pdfr.PdfDocument;
	PdfPage pdfPage = pdfDoc.Pages[0];
	int dpi = 300;
	int dx, dy;
	if (pageInfo.Orientation == PdfSharp.PageOrientation.Portrait)
		{
			dx = (int)(pageInfo.Width.Inch * dpi);
			dy = (int)(pageInfo.Height.Inch * dpi);
		}
	else
		{
			dx = (int)(pageInfo.Height.Inch * dpi);
			dy = (int)(pageInfo.Width.Inch * dpi);
		}
	System.Drawing.Image image = new Bitmap(dx, dy, PixelFormat.Format32bppRgb);
	Graphics graphics = Graphics.FromImage(image);
	graphics.Clear(System.Drawing.Color.White);
	float scale = dpi / 72f;
	graphics.ScaleTransform(scale, scale);
	XGraphics gfx = XGraphics.FromGraphics(graphics, new XSize(pageInfo.Width.Point, pageInfo.Height.Point));
	pdfr.DocumentRenderer.RenderPage(gfx, 1);
	gfx.Dispose();
	return image;
}`

**Comment by TH-Soft** [comment]
Have you tried using "net8.0-windows7.0" instead of "net8.0".
The GDI build requires Windows.

Use the Core build for "net8.0", I think this will work. But the sample code you are showing requires GDI and will not work with the Core build.

**Comment by MarianoJP** [comment]
That is correct. I need to use the GDI in order to build the image preview, but the GDI Nuget Package does not work with net8.0.

**Comment by MarianoJP** [comment]
Or using the Core, how would I render the PDF page to an image in memory? I tried using the XImage but it resulted in an empty png file.

**Comment by TH-Soft** [comment]
Have you tried with "net8.0-windows7.0"?

The GDI package cannot be used with "net6.0" either because it requires "net6.0-windows7.0".

**Comment by MarianoJP** [comment]
I have used the Core with net 8 and it works. I can create pdf files and save them. I want to use the GDI in net 8 to create the image preview. I have tried doing it with an XImage in Core, but I get only a blank PNG.

**Comment by TH-Soft** [comment]
Have you tried using the GDI build with "net8.0-windows7.0"?

**Comment by MarianoJP** [comment]
I cannot find a NuGet Package for PdfSharp-MigraDoc-GID for "net8.0-windows7.0" in NuGet Gallery or from within Visual Studio. Has it been published?

**Comment by TH-Soft** [comment]
Have you tried using the GDI build compiled for "net6.0-windows7.0" with a Blazor project that targets "net8.0-windows7.0"?

The GDI package cannot be used if the Blazor project targets "net8.0" without "-windows7.0" and the error you are showing above will occur.

**Comment by MarianoJP** [comment]
Yes I have used it in the application without the net 8.0 and it works great. The issue is that I need a NuGet GDI Package that targets Net 8, since my blazor project uses another reference that requires it.
________________________________

**Comment by ThomasHoevel** [comment]
As I understand it, the packages that target "net6.0-windows7.0" should also work with projects that target "net8.0-windows7.0".

There is no NuGet package that targets "net8.0-windows7.0", but you can download the source code, change the target frameworks, and create such NuGet packages yourself.

**Comment by MarianoJP** [comment]
Thank you, I will download a clone of the rep and change the net to 8.

________________________________

**Comment by ThomasHoevel** [comment]
OK, I took the MigraDoc sample console application, changed the target to "<TargetFramework>net8.0-windows</TargetFramework>", compiled it, started it, got a PDF.
As far as I can tell, it works as expected.

How do you define "does not work"?

**Comment by MarianoJP** [comment]
Thanks.
________________________________
