### ISSUE TITLE
Reading null Tag on PdfPage throws exception

### ISSUE THREAD

**Issue by raburton** [empira/PDFsharp#59]
Trying to read the Tag value on a PDFPage throws an exception if Tag is null. As this object is for user use, and stated as not being used by PDFSharp, it's value shouldn't be enforced. It's quite possible to want to optionally assign a value to Tag, and later check if that value is null, but doing so causes an exception.

https://github.com/empira/PDFsharp/blob/b748631995b79aedc19b51c42630a20b1353a195/src/foundation/src/PDFsharp/src/PdfSharp/Pdf/PdfPage.cs#L79

**Comment by StLange** [comment]
You are right. The Tag property is now a nullable auto property.
