### ISSUE TITLE
Font Load/Display Issues

### ISSUE THREAD

**Issue by nepgituser** [empira/PDFsharp#6]
Hello,

Just started using PDFsharp for .NET6. Seems quite stable so far. I'm having two issues. The first I'm probably not doing something or doing it wrong. The second seems like it might be a bug. Possibly font related though.

1. Getting a warning when building with the "Arial" font called, possibly all fonts.
info: PdfSharp.Snippets.Font.FailsafeFontResolver[0] 'Arial' bold  was substituted by a SegoeWP font.
```
if (Capabilities.Build.IsCoreBuild)
{
	GlobalFontSettings.FontResolver = new FailsafeFontResolver();
}
var heading = new XFont("Arial", 10, XFontStyleEx.Bold);
```

2. Vertical spacing of fonts doesn't seem to be correct. Spacing slightly favors the bottom.
```
int ypos = 0;
var xf16 = new XFont("Arial", 16, XFontStyleEx.Bold);
Testing(xf16, XBrushes.Teal, ref ypos);
var xf8 = new XFont("Arial", 8, XFontStyleEx.Regular);
Testing(xf8, XBrushes.PaleGreen, ref ypos);
var xf7 = new XFont("Arial", 7, XFontStyleEx.Regular);
Testing(xf7, XBrushes.LightBlue, ref ypos);
_linePosV = 50;

private static void Testing(XFont font, XBrush color, ref int yPos)
{
_gfx.DrawRectangle(color, 0, yPos, 180, font.Height);
_gfx.DrawString($"This Text is Size {font.Size} Font", font, XBrushes.Black, new XRect(0, yPos, 180, font.Height), XStringFormats.Center);
yPos += font.Height;
}
```
![image](https://user-images.githubusercontent.com/118921356/234436681-becb5f62-0f61-49b1-a3be-48091b42f221.png)

Let me know if you need any more info. Thank you for the help and the software.

**Comment by ThomasHoevel** [comment]
> 1. Getting a warning when building with the "Arial" font called, possibly all fonts.
>    info: PdfSharp.Snippets.Font.FailsafeFontResolver[0] 'Arial' bold  was substituted by a SegoeWP font.

You use a FontResolver that uses SegoeWP for every unknown font (including Arial). It's a feature, not a bug. If you want Arial, then use a font resolver that supports Arial.


> 2. Vertical spacing of fonts doesn't seem to be correct. Spacing slightly favors the bottom.

Looks correct. Fonts need room for dots and accents above the letters ("ÄÖÜÁÀ").
There also is `gfx.MeasureString`.
See also:  
http://pdfsharp.net/wiki/TextLayout-sample.ashx  
https://github.com/empira/PDFsharp/blob/master/src/foundation/src/PDFsharp/src/PdfSharp/Drawing.Layout/XTextFormatter.cs

**Comment by nepgituser** [comment]
Thanks for the detailed explanation. The "Arial" font issue was fixed by implementing IFontResolver. Don't generally use fonts like that, so didn't think about it. Makes sense though. That said, "Arial" doesn't seem to leave as much spacing. At any rate, thank you!

**Comment by 2mik** [comment]
Hello,

Thank you for your work of porting the libs to .NET6.
Could you provide an example how to "use a font resolver that supports Arial" ?
Even the [example](https://github.com/empira/PDFsharp.Samples/blob/master/src/samples/src/MigraDoc/src/HelloWorld/Program.cs) that uses Arial actually creates a document with the Segoe font. I've tested the example on Windows 11, Arial is installed.

[FailsafeFontResolver](https://github.com/empira/PDFsharp/blob/master/src/foundation/src/shared/src/PdfSharp.Snippets/Font/fontresolving/FailsafeFontResolver.cs#L24) also tries to load the specified font before Segoe. Despite that, Arial was not loaded.

![font](https://user-images.githubusercontent.com/9930867/235587727-e6c75091-3663-486f-802b-798af7a0913e.png)

**Comment by ThomasHoevel** [comment]
> Could you provide an example how to "use a font resolver that supports Arial"?

A good place to ask this question would be the PDFsharp support forum.

There you can find the EZFontResolver sample:
https://forum.pdfsharp.net/viewtopic.php?f=8&t=3244

And this IFontResolver sample:
https://forum.pdfsharp.net/viewtopic.php?f=8&t=3073

In the PDFsharp source code you can find this sample:
https://github.com/empira/PDFsharp/blob/master/src/foundation/src/shared/src/PdfSharp.Snippets/Font/fontresolving/ExoticFontsFontResolver.cs
https://github.com/empira/PDFsharp/blob/master/src/foundation/src/shared/src/PdfSharp.Snippets/Font/fontresolving/ExoticFontsDataHelper.cs
https://github.com/empira/PDFsharp/blob/master/src/foundation/src/shared/src/PdfSharp.Snippets/Font/fontresolving/ExoticFontResolverSnippet.cs

I admit that these samples do not use "Arial", but replacing "ubuntu" by "Arial" is left as an exercise to the reader.

**Comment by 2mik** [comment]
Thank you.
If anyone is interested, topic is continued [here](https://forum.pdfsharp.net/viewtopic.php?f=2&t=4435)

**Comment by 2mik** [comment]
Just for information, [this](https://closedxml.readthedocs.io/en/latest/features/graphic-engine.html) and [this](https://closedxml.readthedocs.io/en/latest/tips/missing-font.html) links describe the approach for solving the similar font problem, used by [ClosedXML](https://github.com/ClosedXML/ClosedXML) library that generates Excel workbooks.

**Comment by 2mik** [comment]
This font resolver might be useful to someone:

```csharp
#nullable disable

using PdfSharp.Fonts;
using PdfSharp.Snippets.Font;
using PdfSharp.WPFonts;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace PdfSharpTest
{
    public class CustomFontResolver : IFontResolver
    {
        /// <summary>
        /// Identifies a font.
        /// </summary>
        private readonly record struct FontKey(
            string FamilyName,
            bool IsBold,
            bool IsItalic)
        {
            public string GetFaceName() =>
                (string.IsNullOrEmpty(FamilyName) ? "Empty" : FamilyName) +
                (IsBold ? "-Bold" : "") +
                (IsItalic ? "-Italic" : "");
        };

        /// <summary>
        /// Represents information associated with a font.
        /// </summary>
        private class FontMeta
        {
            public string FileName { get; init; }
        }

        /// <summary>
        /// Specifies how to search for the font.
        /// </summary>
        private static readonly EnumerationOptions FontSearchOptions = new()
        {
            RecurseSubdirectories = true,
            MatchCasing = MatchCasing.CaseInsensitive,
            AttributesToSkip = 0,
            IgnoreInaccessible = true
        };


        private readonly SegoeWpFontResolver fallbackFontResolver;
        private readonly Dictionary<string, FontMeta> fontsByFace;


        /// <summary>
        /// Initializes a new instance of the class.
        /// </summary>
        public CustomFontResolver()
        {
            fallbackFontResolver = new SegoeWpFontResolver();
            fontsByFace = new Dictionary<string, FontMeta>();
        }


        /// <summary>
        /// Finds the specified font in the file system.
        /// </summary>
        private static FontResolverInfo FindFont(FontKey fontKey, out string fileName)
        {
            if (string.IsNullOrEmpty(fontKey.FamilyName))
            {
                fileName = "";
                return null;
            }

            try
            {
                ICollection<string> fontDirectories = GetFontDirectories();
                ICollection<string> desiredNames = GetDesiredNames(fontKey);
                ICollection<string> candidateNames = GetCandidateNames(fontKey);
                FileInfo candidateFileInfo = null;

                foreach (string fontDirectory in fontDirectories)
                {
                    if (!Directory.Exists(fontDirectory))
                        continue;

                    foreach (FileInfo fileInfo in new DirectoryInfo(fontDirectory)
                        .EnumerateFiles(fontKey.FamilyName + "*.ttf", FontSearchOptions))
                    {
                        if (desiredNames.Any(name => name.Equals(fileInfo.Name, StringComparison.OrdinalIgnoreCase)))
                        {
                            fileName = fileInfo.FullName;
                            return new FontResolverInfo(fontKey.GetFaceName(), false, false);
                        }

                        if (candidateFileInfo == null &&
                            candidateNames.Any(name => name.Equals(fileInfo.Name, StringComparison.OrdinalIgnoreCase)))
                        {
                            candidateFileInfo = fileInfo;
                        }
                    }
                }

                if (candidateFileInfo != null)
                {
                    fileName = candidateFileInfo.FullName;
                    return new FontResolverInfo(fontKey.GetFaceName(), fontKey.IsBold, fontKey.IsItalic);
                }
            }
            catch (Exception ex)
            {
                Debug.WriteLine(ex);
            }

            fileName = "";
            return null;
        }

        /// <summary>
        /// Gets the font directories depending on the OS.
        /// </summary>
        private static ICollection<string> GetFontDirectories()
        {
            if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
            {
                return new string[]
                {
                    @"C:\Windows\Fonts\",
                    Path.Combine(
                        Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),
                        @"Microsoft\Windows\Fonts")
                };
            }
            else if (RuntimeInformation.IsOSPlatform(OSPlatform.Linux))
            {
                return new string[]
                {
                    "/usr/share/fonts/truetype/"
                };
            }
            else
            {
                return Array.Empty<string>();
            }
        }

        /// <summary>
        /// Gets desired font file names.
        /// </summary>
        private static ICollection<string> GetDesiredNames(FontKey fontKey)
        {
            if (fontKey.IsBold && fontKey.IsItalic)
            {
                return new string[]
                {
                    fontKey.FamilyName + "bi.ttf",
                    fontKey.FamilyName + "-BoldItalic.ttf",
                    fontKey.FamilyName + "-BoldOblique.ttf"
                };
            }
            else if (fontKey.IsBold)
            {
                return new string[]
                {
                    fontKey.FamilyName + "bd.ttf",
                    fontKey.FamilyName + "-Bold.ttf"
                };
            }
            else if (fontKey.IsItalic)
            {
                return new string[]
                {
                    fontKey.FamilyName + "i.ttf",
                    fontKey.FamilyName + "-Italic.ttf",
                    fontKey.FamilyName + "-Oblique.ttf"
                };
            }
            else
            {
                return new string[]
                {
                    fontKey.FamilyName + ".ttf",
                    fontKey.FamilyName + "-Regular.ttf"
                };
            }
        }

        /// <summary>
        /// Gets possible font file names.
        /// </summary>
        private static ICollection<string> GetCandidateNames(FontKey fontKey)
        {
            if (fontKey.IsBold || fontKey.IsItalic)
            {
                return new string[]
                {
                    fontKey.FamilyName + ".ttf",
                    fontKey.FamilyName + "-Regular.ttf"
                };
            }
            else
            {
                return Array.Empty<string>();
            }
        }


        /// <summary>
        /// Converts specified information about a required typeface into a specific font.
        /// </summary>
        /// <remarks>
        /// PDFsharp calls ResolveTypeface only once for each unique combination of familyName, isBold, and isItalic.
        /// </remarks>
        public FontResolverInfo ResolveTypeface(string familyName, bool isBold, bool isItalic)
        {
            FontKey fontKey = new(familyName, isBold, isItalic);
            FontResolverInfo resolverInfo =
                FindFont(fontKey, out string fileName) ??
                fallbackFontResolver.ResolveTypeface(isBold
                    ? SegoeWpFontResolver.FamilyNames.SegoeWPBold
                    : SegoeWpFontResolver.FamilyNames.SegoeWP,
                    false, isItalic) ??
                new FontResolverInfo(fontKey.GetFaceName(), isBold, isItalic);

            fontsByFace[resolverInfo.FaceName] = new FontMeta { FileName = fileName };
            return resolverInfo;
        }

        /// <summary>
        /// Gets the bytes of a physical font with specified face name.
        /// </summary>
        /// <remarks>
        /// A face name previously retrieved by ResolveTypeface.
        /// PDFsharp never calls GetFont twice with the same face name.
        /// </remarks>
        public byte[] GetFont(string faceName)
        {
            try
            {
                if (fontsByFace.TryGetValue(faceName, out FontMeta fontMeta))
                {
                    byte[] font = string.IsNullOrEmpty(fontMeta.FileName)
                        ? fallbackFontResolver.GetFont(faceName)
                        : File.ReadAllBytes(fontMeta.FileName);

                    if (font != null)
                        return font;
                }
            }
            catch (Exception ex)
            {
                Debug.WriteLine(ex);
            }

            return FontDataHelper.SegoeWP;
        }
    }
}
```

**Comment by ThomasHoevel** [comment]
> This font resolver might be useful to someone:

The `NewFontResolver` that comes with PDFsharp might be useful, too. It was tested with Windows and Linux, but not with MacOS.
See:
src/foundation/src/shared/src/PdfSharp.Snippets/Font/fontresolving/NewFontResolver.cs

https://github.com/empira/PDFsharp/blob/d751497c3484fae9da4ae263568df00dc9554773/src/foundation/src/shared/src/PdfSharp.Snippets/Font/fontresolving/NewFontResolver.cs#L6

The name might change with future releases of PDFsharp.

**Comment by 2mik** [comment]
Thank you. I used NewFontResolver as an example to develop CustomFontResolver. The key difference is that NewFontResolver contains the predefined list of fonts, while CustomFontResolver can load any existing font.

**Comment by ckpearson** [comment]
> This font resolver might be useful to someone:
> 
> ```cs
> #nullable disable
> 
> using PdfSharp.Fonts;
> using PdfSharp.Snippets.Font;
> using PdfSharp.WPFonts;
> using System.Diagnostics;
> using System.Runtime.InteropServices;
> 
> namespace PdfSharpTest
> {
>     public class CustomFontResolver : IFontResolver
>     {
>         /// <summary>
>         /// Identifies a font.
>         /// </summary>
>         private readonly record struct FontKey(
>             string FamilyName,
>             bool IsBold,
>             bool IsItalic)
>         {
>             public string GetFaceName() =>
>                 (string.IsNullOrEmpty(FamilyName) ? "Empty" : FamilyName) +
>                 (IsBold ? "-Bold" : "") +
>                 (IsItalic ? "-Italic" : "");
>         };
> 
>         /// <summary>
>         /// Represents information associated with a font.
>         /// </summary>
>         private class FontMeta
>         {
>             public string FileName { get; init; }
>         }
> 
>         /// <summary>
>         /// Specifies how to search for the font.
>         /// </summary>
>         private static readonly EnumerationOptions FontSearchOptions = new()
>         {
>             RecurseSubdirectories = true,
>             MatchCasing = MatchCasing.CaseInsensitive,
>             AttributesToSkip = 0,
>             IgnoreInaccessible = true
>         };
> 
> 
>         private readonly SegoeWpFontResolver fallbackFontResolver;
>         private readonly Dictionary<string, FontMeta> fontsByFace;
> 
> 
>         /// <summary>
>         /// Initializes a new instance of the class.
>         /// </summary>
>         public CustomFontResolver()
>         {
>             fallbackFontResolver = new SegoeWpFontResolver();
>             fontsByFace = new Dictionary<string, FontMeta>();
>         }
> 
> 
>         /// <summary>
>         /// Finds the specified font in the file system.
>         /// </summary>
>         private static FontResolverInfo FindFont(FontKey fontKey, out string fileName)
>         {
>             if (string.IsNullOrEmpty(fontKey.FamilyName))
>             {
>                 fileName = "";
>                 return null;
>             }
> 
>             try
>             {
>                 ICollection<string> fontDirectories = GetFontDirectories();
>                 ICollection<string> desiredNames = GetDesiredNames(fontKey);
>                 ICollection<string> candidateNames = GetCandidateNames(fontKey);
>                 FileInfo candidateFileInfo = null;
> 
>                 foreach (string fontDirectory in fontDirectories)
>                 {
>                     if (!Directory.Exists(fontDirectory))
>                         continue;
> 
>                     foreach (FileInfo fileInfo in new DirectoryInfo(fontDirectory)
>                         .EnumerateFiles(fontKey.FamilyName + "*.ttf", FontSearchOptions))
>                     {
>                         if (desiredNames.Any(name => name.Equals(fileInfo.Name, StringComparison.OrdinalIgnoreCase)))
>                         {
>                             fileName = fileInfo.FullName;
>                             return new FontResolverInfo(fontKey.GetFaceName(), false, false);
>                         }
> 
>                         if (candidateFileInfo == null &&
>                             candidateNames.Any(name => name.Equals(fileInfo.Name, StringComparison.OrdinalIgnoreCase)))
>                         {
>                             candidateFileInfo = fileInfo;
>                         }
>                     }
>                 }
> 
>                 if (candidateFileInfo != null)
>                 {
>                     fileName = candidateFileInfo.FullName;
>                     return new FontResolverInfo(fontKey.GetFaceName(), fontKey.IsBold, fontKey.IsItalic);
>                 }
>             }
>             catch (Exception ex)
>             {
>                 Debug.WriteLine(ex);
>             }
> 
>             fileName = "";
>             return null;
>         }
> 
>         /// <summary>
>         /// Gets the font directories depending on the OS.
>         /// </summary>
>         private static ICollection<string> GetFontDirectories()
>         {
>             if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
>             {
>                 return new string[]
>                 {
>                     @"C:\Windows\Fonts\",
>                     Path.Combine(
>                         Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),
>                         @"Microsoft\Windows\Fonts")
>                 };
>             }
>             else if (RuntimeInformation.IsOSPlatform(OSPlatform.Linux))
>             {
>                 return new string[]
>                 {
>                     "/usr/share/fonts/truetype/"
>                 };
>             }
>             else
>             {
>                 return Array.Empty<string>();
>             }
>         }
> 
>         /// <summary>
>         /// Gets desired font file names.
>         /// </summary>
>         private static ICollection<string> GetDesiredNames(FontKey fontKey)
>         {
>             if (fontKey.IsBold && fontKey.IsItalic)
>             {
>                 return new string[]
>                 {
>                     fontKey.FamilyName + "bi.ttf",
>                     fontKey.FamilyName + "-BoldItalic.ttf",
>                     fontKey.FamilyName + "-BoldOblique.ttf"
>                 };
>             }
>             else if (fontKey.IsBold)
>             {
>                 return new string[]
>                 {
>                     fontKey.FamilyName + "bd.ttf",
>                     fontKey.FamilyName + "-Bold.ttf"
>                 };
>             }
>             else if (fontKey.IsItalic)
>             {
>                 return new string[]
>                 {
>                     fontKey.FamilyName + "i.ttf",
>                     fontKey.FamilyName + "-Italic.ttf",
>                     fontKey.FamilyName + "-Oblique.ttf"
>                 };
>             }
>             else
>             {
>                 return new string[]
>                 {
>                     fontKey.FamilyName + ".ttf",
>                     fontKey.FamilyName + "-Regular.ttf"
>                 };
>             }
>         }
> 
>         /// <summary>
>         /// Gets possible font file names.
>         /// </summary>
>         private static ICollection<string> GetCandidateNames(FontKey fontKey)
>         {
>             if (fontKey.IsBold || fontKey.IsItalic)
>             {
>                 return new string[]
>                 {
>                     fontKey.FamilyName + ".ttf",
>                     fontKey.FamilyName + "-Regular.ttf"
>                 };
>             }
>             else
>             {
>                 return Array.Empty<string>();
>             }
>         }
> 
> 
>         /// <summary>
>         /// Converts specified information about a required typeface into a specific font.
>         /// </summary>
>         /// <remarks>
>         /// PDFsharp calls ResolveTypeface only once for each unique combination of familyName, isBold, and isItalic.
>         /// </remarks>
>         public FontResolverInfo ResolveTypeface(string familyName, bool isBold, bool isItalic)
>         {
>             FontKey fontKey = new(familyName, isBold, isItalic);
>             FontResolverInfo resolverInfo =
>                 FindFont(fontKey, out string fileName) ??
>                 fallbackFontResolver.ResolveTypeface(isBold
>                     ? SegoeWpFontResolver.FamilyNames.SegoeWPBold
>                     : SegoeWpFontResolver.FamilyNames.SegoeWP,
>                     false, isItalic) ??
>                 new FontResolverInfo(fontKey.GetFaceName(), isBold, isItalic);
> 
>             fontsByFace[resolverInfo.FaceName] = new FontMeta { FileName = fileName };
>             return resolverInfo;
>         }
> 
>         /// <summary>
>         /// Gets the bytes of a physical font with specified face name.
>         /// </summary>
>         /// <remarks>
>         /// A face name previously retrieved by ResolveTypeface.
>         /// PDFsharp never calls GetFont twice with the same face name.
>         /// </remarks>
>         public byte[] GetFont(string faceName)
>         {
>             try
>             {
>                 if (fontsByFace.TryGetValue(faceName, out FontMeta fontMeta))
>                 {
>                     byte[] font = string.IsNullOrEmpty(fontMeta.FileName)
>                         ? fallbackFontResolver.GetFont(faceName)
>                         : File.ReadAllBytes(fontMeta.FileName);
> 
>                     if (font != null)
>                         return font;
>                 }
>             }
>             catch (Exception ex)
>             {
>                 Debug.WriteLine(ex);
>             }
> 
>             return FontDataHelper.SegoeWP;
>         }
>     }
> }
> ```

You're an absolute lifesaver, this has just helped solve our issue, really like that it resolves based on installed fonts.

**Comment by Thar2022** [comment]
Thank you very much.

**Comment by hurui79** [comment]
> 这个字体解析器或许对某些人有用：
> 
> #nullable disable
> 
> using PdfSharp.Fonts;
> using PdfSharp.Snippets.Font;
> using PdfSharp.WPFonts;
> using System.Diagnostics;
> using System.Runtime.InteropServices;
> 
> namespace PdfSharpTest
> {
>     public class CustomFontResolver : IFontResolver
>     {
>         /// <summary>
>         /// Identifies a font.
>         /// </summary>
>         private readonly record struct FontKey(
>             string FamilyName,
>             bool IsBold,
>             bool IsItalic)
>         {
>             public string GetFaceName() =>
>                 (string.IsNullOrEmpty(FamilyName) ? "Empty" : FamilyName) +
>                 (IsBold ? "-Bold" : "") +
>                 (IsItalic ? "-Italic" : "");
>         };
> 
>         /// <summary>
>         /// Represents information associated with a font.
>         /// </summary>
>         private class FontMeta
>         {
>             public string FileName { get; init; }
>         }
> 
>         /// <summary>
>         /// Specifies how to search for the font.
>         /// </summary>
>         private static readonly EnumerationOptions FontSearchOptions = new()
>         {
>             RecurseSubdirectories = true,
>             MatchCasing = MatchCasing.CaseInsensitive,
>             AttributesToSkip = 0,
>             IgnoreInaccessible = true
>         };
> 
> 
>         private readonly SegoeWpFontResolver fallbackFontResolver;
>         private readonly Dictionary<string, FontMeta> fontsByFace;
> 
> 
>         /// <summary>
>         /// Initializes a new instance of the class.
>         /// </summary>
>         public CustomFontResolver()
>         {
>             fallbackFontResolver = new SegoeWpFontResolver();
>             fontsByFace = new Dictionary<string, FontMeta>();
>         }
> 
> 
>         /// <summary>
>         /// Finds the specified font in the file system.
>         /// </summary>
>         private static FontResolverInfo FindFont(FontKey fontKey, out string fileName)
>         {
>             if (string.IsNullOrEmpty(fontKey.FamilyName))
>             {
>                 fileName = "";
>                 return null;
>             }
> 
>             try
>             {
>                 ICollection<string> fontDirectories = GetFontDirectories();
>                 ICollection<string> desiredNames = GetDesiredNames(fontKey);
>                 ICollection<string> candidateNames = GetCandidateNames(fontKey);
>                 FileInfo candidateFileInfo = null;
> 
>                 foreach (string fontDirectory in fontDirectories)
>                 {
>                     if (!Directory.Exists(fontDirectory))
>                         continue;
> 
>                     foreach (FileInfo fileInfo in new DirectoryInfo(fontDirectory)
>                         .EnumerateFiles(fontKey.FamilyName + "*.ttf", FontSearchOptions))
>                     {
>                         if (desiredNames.Any(name => name.Equals(fileInfo.Name, StringComparison.OrdinalIgnoreCase)))
>                         {
>                             fileName = fileInfo.FullName;
>                             return new FontResolverInfo(fontKey.GetFaceName(), false, false);
>                         }
> 
>                         if (candidateFileInfo == null &&
>                             candidateNames.Any(name => name.Equals(fileInfo.Name, StringComparison.OrdinalIgnoreCase)))
>                         {
>                             candidateFileInfo = fileInfo;
>                         }
>                     }
>                 }
> 
>                 if (candidateFileInfo != null)
>                 {
>                     fileName = candidateFileInfo.FullName;
>                     return new FontResolverInfo(fontKey.GetFaceName(), fontKey.IsBold, fontKey.IsItalic);
>                 }
>             }
>             catch (Exception ex)
>             {
>                 Debug.WriteLine(ex);
>             }
> 
>             fileName = "";
>             return null;
>         }
> 
>         /// <summary>
>         /// Gets the font directories depending on the OS.
>         /// </summary>
>         private static ICollection<string> GetFontDirectories()
>         {
>             if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
>             {
>                 return new string[]
>                 {
>                     @"C:\Windows\Fonts\",
>                     Path.Combine(
>                         Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),
>                         @"Microsoft\Windows\Fonts")
>                 };
>             }
>             else if (RuntimeInformation.IsOSPlatform(OSPlatform.Linux))
>             {
>                 return new string[]
>                 {
>                     "/usr/share/fonts/truetype/"
>                 };
>             }
>             else
>             {
>                 return Array.Empty<string>();
>             }
>         }
> 
>         /// <summary>
>         /// Gets desired font file names.
>         /// </summary>
>         private static ICollection<string> GetDesiredNames(FontKey fontKey)
>         {
>             if (fontKey.IsBold && fontKey.IsItalic)
>             {
>                 return new string[]
>                 {
>                     fontKey.FamilyName + "bi.ttf",
>                     fontKey.FamilyName + "-BoldItalic.ttf",
>                     fontKey.FamilyName + "-BoldOblique.ttf"
>                 };
>             }
>             else if (fontKey.IsBold)
>             {
>                 return new string[]
>                 {
>                     fontKey.FamilyName + "bd.ttf",
>                     fontKey.FamilyName + "-Bold.ttf"
>                 };
>             }
>             else if (fontKey.IsItalic)
>             {
>                 return new string[]
>                 {
>                     fontKey.FamilyName + "i.ttf",
>                     fontKey.FamilyName + "-Italic.ttf",
>                     fontKey.FamilyName + "-Oblique.ttf"
>                 };
>             }
>             else
>             {
>                 return new string[]
>                 {
>                     fontKey.FamilyName + ".ttf",
>                     fontKey.FamilyName + "-Regular.ttf"
>                 };
>             }
>         }
> 
>         /// <summary>
>         /// Gets possible font file names.
>         /// </summary>
>         private static ICollection<string> GetCandidateNames(FontKey fontKey)
>         {
>             if (fontKey.IsBold || fontKey.IsItalic)
>             {
>                 return new string[]
>                 {
>                     fontKey.FamilyName + ".ttf",
>                     fontKey.FamilyName + "-Regular.ttf"
>                 };
>             }
>             else
>             {
>                 return Array.Empty<string>();
>             }
>         }
> 
> 
>         /// <summary>
>         /// Converts specified information about a required typeface into a specific font.
>         /// </summary>
>         /// <remarks>
>         /// PDFsharp calls ResolveTypeface only once for each unique combination of familyName, isBold, and isItalic.
>         /// </remarks>
>         public FontResolverInfo ResolveTypeface(string familyName, bool isBold, bool isItalic)
>         {
>             FontKey fontKey = new(familyName, isBold, isItalic);
>             FontResolverInfo resolverInfo =
>                 FindFont(fontKey, out string fileName) ??
>                 fallbackFontResolver.ResolveTypeface(isBold
>                     ? SegoeWpFontResolver.FamilyNames.SegoeWPBold
>                     : SegoeWpFontResolver.FamilyNames.SegoeWP,
>                     false, isItalic) ??
>                 new FontResolverInfo(fontKey.GetFaceName(), isBold, isItalic);
> 
>             fontsByFace[resolverInfo.FaceName] = new FontMeta { FileName = fileName };
>             return resolverInfo;
>         }
> 
>         /// <summary>
>         /// Gets the bytes of a physical font with specified face name.
>         /// </summary>
>         /// <remarks>
>         /// A face name previously retrieved by ResolveTypeface.
>         /// PDFsharp never calls GetFont twice with the same face name.
>         /// </remarks>
>         public byte[] GetFont(string faceName)
>         {
>             try
>             {
>                 if (fontsByFace.TryGetValue(faceName, out FontMeta fontMeta))
>                 {
>                     byte[] font = string.IsNullOrEmpty(fontMeta.FileName)
>                         ? fallbackFontResolver.GetFont(faceName)
>                         : File.ReadAllBytes(fontMeta.FileName);
> 
>                     if (font != null)
>                         return font;
>                 }
>             }
>             catch (Exception ex)
>             {
>                 Debug.WriteLine(ex);
>             }
> 
>             return FontDataHelper.SegoeWP;
>         }
>     }
> }

感谢！
