### ISSUE TITLE
Incorrectly combined path in NewFontResolver

### ISSUE THREAD

**Issue by Nestastnikos** [empira/PDFsharp#60]
# Reporting an Issue Here
NewFontResolver uses `Path.Combine` to construct a path pointing to fonts installed in user profile folder.
https://github.com/empira/PDFsharp/blob/b748631995b79aedc19b51c42630a20b1353a195/src/foundation/src/shared/src/PdfSharp.Snippets/Font/fontresolving/NewFontResolver.cs#L191

However, the paths, which should be combined with the user profile folder are specified as absolute (because starts with `/`), resulting in incorrectly combined path in the final result. The final path will always consist only from the second path without the user profile folder as [documentation](https://learn.microsoft.com/en-us/dotnet/api/system.io.path.combine?view=net-6.0) for `Path.Combine` states:
```
If the one of the subsequent paths is an absolute path, then the combine operation resets starting with that absolute path, discarding all previous combined paths.
```

## Expected Behavior
The combined path consists of user profile folder concatenated with `.fonts` folder.
## Actual Behavior
The path consists of only of `/.fonts`.
## Steps to Reproduce the Behavior
1. Precondition: On the linux machine, install some font to `$HOME/.fonts` folder. The font should not be available on any other place in the system.
2. Register the font family to `NewFontResolver.Families`.
3. Try to use the font when rendering the text.

**Comment by ThomasHoevel** [comment]
Issue was fixed.
