### ISSUE TITLE
XImage.PointHeight returning width

### ISSUE THREAD

**Issue by julienrffr** [empira/PDFsharp#61]
## Expected Behavior

XImage.PointHeight returning **height**...

## Actual Behavior

XImage.PointHeight returns **width**...

## Steps to Reproduce the Behavior
Get XImage.PointHeight from \src\foundation\src\PDFsharp\src\PdfSharp\Drawing\XImage.cs

https://github.com/empira/PDFsharp/blob/b748631995b79aedc19b51c42630a20b1353a195/src/foundation/src/PDFsharp/src/PdfSharp/Drawing/XImage.cs#L942

![image](https://github.com/empira/PDFsharp/assets/90320494/79324140-cdc6-488a-8439-3573de0d80fe)

**Comment by ThomasHoevel** [comment]
Thanks for the feedback. Fixed it in the current internal build.
Will be fixed with the next release.
