### ISSUE TITLE
PDF generation succeeds, but fails silently on specific page  

### ISSUE THREAD

**Issue by DunnJM** [empira/PDFsharp#62]
## Expected Behavior
- PdfReader.Open to produce PdfDocument object with expected number of pages

## Actual Behavior
- PdfDocument produced, but only 3/34 pages generated with the 3rd page being an error
- Removing the third page allows the pdf to generate all other pages

## Steps to Reproduce the Behavior
- Run the PDFsharp IssueSubmission console app
- Navigate to {temp folder}\pdf-test
- Open test-output.pdf

[Issue.zip](https://github.com/empira/PDFsharp/files/13588437/Issue.zip)

**Comment by ThomasHoevel** [comment]
Could be a duplicate, so I close this issue.
https://github.com/empira/PDFsharp/issues/46#issue-1947873727

**Comment by DunnJM** [comment]
Hey @ThomasHoevel !
I would say It's not a duplicate, the problem raised on the other issue relates to duplicate pages, of which this PDF has none.
The behaviour here is quite different, in that pdf production succeeds but actually it has failed on the third page.
Please can you re-open the issue.
Thanks!

**Comment by ThomasHoevel** [comment]
I don't know if it is a duplicate, but I prefer to have PdfReader.Open problems in one issue until I am sure they are unrelated.

**Comment by DunnJM** [comment]
@ThomasHoevel Ok, no worries!
Is there any way to work around this by, for example, continuing on page failure or by targeting only specific pages when opening the pdf?

**Comment by ThomasHoevel** [comment]
PDFsharp reads the complete document on opening, so there is no easy work-around.

**Comment by ThomasHoevel** [comment]
This is definitely a duplicate. With the patch offered by Packdat, the file can be opened with all 34 pages.

**Comment by DunnJM** [comment]
@ThomasHoevel thanks for taking a look!
Is there any word on the release of that patch?

**Comment by ThomasHoevel** [comment]
> Is there any word on the release of that patch?

https://github.com/empira/PDFsharp/issues/46#issuecomment-1809645309
