### ISSUE TITLE
.NET Standard Support

### ISSUE THREAD

**Issue by InteXX** [empira/PDFsharp#63]
Would it be possible to add .NET Standard 2.0 to the supported frameworks?

I'm managing an old WebForms project and I need .NET Framework support (4.8 in my case).

**Comment by TH-Soft** [comment]
It's possible. Will come with PDFsharp 6.1.0.

https://github.com/empira/PDFsharp/pull/45#issue-1945425646

**Comment by InteXX** [comment]
Thank you, Thomas.
