### ISSUE TITLE
Unicode "Estimates" not printing

### ISSUE THREAD

**Issue by tkolb-recom** [empira/PDFsharp#65]
I tried the recent PDFsharp lib to evaluate whether a serious problem with v1.5 was addressed meanwhile.
Some issued characters are now not resulting in exceptions anymore but I stumbled upon the following.

## Expected Behavior

Unicode [≙ (U+2259)](https://www.fileformat.info/info/unicode/char/2259/index.htm) should be printed 

That code is [explicitly supported](https://www.fileformat.info/info/unicode/char/2259/fontsupport.htm) with Arial Unicode and Cambria Math

## Actual Behavior
Displayed Unicodes are U+2259 (Estimates), U+221E (Infinity), and U+2211 (Sum)

![image](https://github.com/empira/PDFsharp/assets/61977109/3dc6991f-ca78-4f7e-a08a-dfa5bbb1e41e)

## Steps to Reproduce the Behavior

run that IssueSubmission program:

https://github.com/tkolb-recom/PDFsharp.IssueSubmissionTemplate/commit/0caa601e21a7bc8737585a7d75b6c2faa2737beb
https://github.com/tkolb-recom/PDFsharp.IssueSubmissionTemplate/releases/tag/tagEstimates -- [ZIP-Download](https://github.com/tkolb-recom/PDFsharp.IssueSubmissionTemplate/archive/refs/tags/tagEstimates.zip)

**Comment by ThomasHoevel** [comment]
Cambria Math is a True Type Font Collection and not yet supported by PDFsharp.

Arial Unicode MS works as expected when the correct font files are used (I tried the WPF build under Windows 10).

![image](https://github.com/empira/PDFsharp/assets/15982318/33cd21bd-791a-46ad-99fb-9bcd356d6601)

**Comment by tkolb-recom** [comment]
> Cambria Math is a True Type Font Collection and not yet supported by PDFsharp.
> 
> Arial Unicode MS works as expected when the correct font files are used (I tried the WPF build under Windows 10).

Sorry for being late on this, there were some holidays/vacation in between. 
What are the "correct font files"? I did not change any fonts in windows. What's the different in the example project?

I think it should not matter: We do not use WPF. We are sadly somehow still bound to WinForms.

Edit:
I see now, when using the GDI/WPF assemblies the resolved font actually is not what was requested. However when using the plain project it printed the font name like it was requested but actually is not the right font.
