### ISSUE TITLE
Unsupported image format exception 

### ISSUE THREAD

**Issue by stefancata26** [empira/PDFsharp#66]
I am trying to print a QR code to a pdf document. I used the QRCoder library to convert a string to png byte array. 
Why is the line "XImage qrCodeImage = XImage.FromStream(qrCodeStream);" throwing an "Unsupported image format." exception?
This was working in PDF sharp version 1.50.5147, but after upgrading to version 6.0.0 it stopped working. 

public class GeneratePdf
{
    byte[] pdfData;

    public byte[] PaymentLinkToPngQrCode(string paymentLink)
    {
        QRCodeGenerator qrGenerator = new QRCodeGenerator();
        QRCodeData qrCodeData = qrGenerator.CreateQrCode(paymentLink, QRCodeGenerator.ECCLevel.Q);
        PngByteQRCode qrCode = new PngByteQRCode(qrCodeData);
        byte[] qrCodeAsPngByteArr = qrCode.GetGraphic(10);

        return qrCodeAsPngByteArr;
    } 

   public async Task<byte[]> GeneratePdfWithQrCode(string paymentLink)
    {   
        try
        {
            // Create a new PDF document
            PdfDocument document = new PdfDocument();
            PdfPage page = document.AddPage();
            XGraphics gfx = XGraphics.FromPdfPage(page);

            // Generate the QR code image from the payment link
            byte[] qrCodeAsPngByteArr = PaymentLinkToPngQrCode(paymentLink);

            // Create a bitmap from the QR code byte array
            using (var qrCodeStream = new MemoryStream(qrCodeAsPngByteArr, 0, qrCodeAsPngByteArr.Length, false, true))
            {
                XImage qrCodeImage = XImage.FromStream(qrCodeStream);

                // Draw the QR code image on the PDF page
                gfx.DrawImage(qrCodeImage, new XRect(100, 100, 100, 100)); 

                using (MemoryStream pdfStream = new MemoryStream())
                {
                    // Save the PDF document into the MemoryStream
                    document.Save(pdfStream, false);

                    // Get the PDF content as a byte array
                    return pdfStream.ToArray();
                }
                 Console.WriteLine("PDF saved successfully.");
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine("Error: " + ex.Message);
            return null;
        }   
    }

**Comment by TH-Soft** [comment]
Try the WPF or GDI build of PDFsharp, not the Core build.

**Comment by stefancata26** [comment]
> Try the WPF or GDI build of PDFsharp, not the Core build.

I have an aspnet core project not wpf. The problem is that is telling me that the format is unsupported, even though the QR format is a png.

**Comment by TH-Soft** [comment]
If it was working with PDFsharp 1.50, then try the GDI build or the WPF build. PDFsharp 1.50 was using GDI for images. This works if your project is running under Windows.

Or use code to convert the PNG to a supported PNG format. That's an option if you need support for Linux or Mac.
