### ISSUE TITLE
CodeOmr not usable caused by a specific hack

### ISSUE THREAD

**Issue by Steffen-M** [empira/PDFsharp#7]
It looks like a specific hack went into the generic production code.
File `src\foundation\src\PDFsharp\src\PdfSharp\Drawing.BarCodes\CodeOmr.cs`
```
#if true
            // HACK: Project Wallenwein: set LK
            value |= 1;
            _synchronizeCode = true;
#endif
```

Best Regards,
Steffen

**Comment by ThomasHoevel** [comment]
The hack was removed with current version 6.0.0.
I hope this issue is resolved.
