### ISSUE TITLE
Unable to change the document page header margin

### ISSUE THREAD

**Issue by wallid** [empira/PDFsharp#75]
Not sure this is the correct type or label. I've tried changing the header margin on a document but there isn't any setters for me. I was wondering if someone was able to change the margins on a header. I can do it on a section but not on the document header.

Thanks.

# Resources

The official project web site:  
https://docs.pdfsharp.net/

The official peer-to-peer support forum:  
http://forum.pdfsharp.net/

# Reporting an Issue Here
## Steps to Reproduce the Behavior
We strongly recommend using the IssueSubmissionTemplate to make sure we can replicate the issue.  
https://docs.pdfsharp.net/General/IssueReporting.html

**Comment by TH-Soft** [comment]
Not many details.

**Comment by wallid** [comment]
Not sure this is the correct type or label. I've tried changing the header margin on a document but there isn't any setters for me. I was wondering if someone was able to change the margins on a header. I can do it on a section but not on the document header.

Thanks.

**Comment by TH-Soft** [comment]
You can set the Header distance and the Top margin in the PageSetup. The PageSetup applies to all pages of a Section.
