### ISSUE TITLE
PNG color type 4 (grayscale with alpha) not implemented => throwing exception

### ISSUE THREAD

**Issue by julienrffr** [empira/PDFsharp#78]
On Core build, when displaying a PNG image, an exception is thrown due to this missing case in the switch of ImageImporterPng:
https://github.com/empira/PDFsharp/blob/b28bc3265e0a15302c04b7b91da0d915a591e167/src/foundation/src/PDFsharp/src/PdfSharp/Drawing.Internal/ImageImporterPng.cs#L154

Color type 4 is grayscale with alpha (see [PNG specs](https://www.w3.org/TR/PNG-Chunks.html))

Find attached a PNG image that triggers this not-implemented case.
![Aalto_company_logo](https://github.com/empira/PDFsharp/assets/90320494/cfe544d6-2ef2-43b4-8a4c-bd27b6e87bcb)

Do you have an ETA for this to be implemented?

Note that doint the same thing as case 6 works well (at least for the attached image).
`ii.Information.ImageFormat = ImageInformation.ImageFormats.ARGB32;`

To test, just add those lines to the HelloWorld program.cs:
`var imageStream = File.Open(@"C:\Users\xxx\Downloads\Aalto_company_logo.png", FileMode.Open, FileAccess.Read);XImage xImage = XImage.FromStream(imageStream);
            gfx.DrawImage(xImage, 0, 0, 100, 100);`

**Comment by TH-Soft** [comment]
There is no ETA.
This works with the GDI and WPF builds.
This works with the Core build when a BMP file is used.

**Comment by ThomasHoevel** [comment]
Issue should be resolved with PDFsharp 6.2.0 Preview 2.
