### ISSUE TITLE
MemoryStream's internal buffer cannot be accessed.

### ISSUE THREAD

**Issue by iPazooki** [empira/PDFsharp#90]
I'm using **.NET 8** and use the latest version of the PDFSharp (6 and 6.1pre) but I'm getting this error "_MemoryStream's internal buffer cannot be accessed._" when I use this code:

```csharp
var contentSteam = new MemoryStream(imageForPage);
            
XImage contentXImage = XImage.FromStream(contentSteam);
```

**Comment by ThomasHoevel** [comment]
You are using the wrong c'tor.

Use this c'tor to make the buffer accessible by setting the "publiclyVisible" parameter to true:  
`new MemoryStream(bytes, 0, bytes.Length, true, true)`

"publiclyVisible" is the fifth parameter here. The value of the forth parameter probably makes no difference.

**Comment by flensrocker** [comment]
"writeable" seems not to be needed, "publiclyVisible" is needed.

**Comment by ThomasHoevel** [comment]
> "writeable" seems not to be needed, "publiclyVisible" is needed.

"Accessible" is the keyword and in this context it means "visible".

"writeable" is true by default and will be set when a c'tor without it is used.
"accessible" is false by default and will not be set when a c'tor without it is used.

**Comment by flensrocker** [comment]
Noone mentioned "writeable" above, I just stumbled upon the same problem and didn't want my image data to be writable, so I tested `new MemoryStream(bytes, 0, bytes.Length, false, true)` and that worked, too.

So I just wanted to mention that, if you want to restrict access as far as possible.
