### ISSUE TITLE
there have a problem in 6.1.0-preview-2

### ISSUE THREAD

**Issue by Suddenly-TurnRound** [empira/PDFsharp#98]
there have a problem in 
6.1.0-preview-2

**Comment by youkai199407017** [comment]
byte[] updatedPdfByte = null;
                using (var pdfStream = new MemoryStream(pdfAsByteArray))
                {
                    using var document = PdfReader.Open(pdfStream, PdfDocumentOpenMode.Modify);
                    var pageCount = document.PageCount;
                    var pageWidth = document.Pages[0].Width;
                    var pageHeight = document.Pages[0].Height;
                    PdfPage page = null;

                    var coverItem = pageList[0];
                    var pageIndex = coverItem.ToIndex > 0 ? coverItem.ToIndex - 1 : pageCount - 1;
                    page = document.Pages[pageIndex];

                    byte[] imageBytes = Convert.FromBase64String(imageBase64s[0]);
                    using (var imgStream = new MemoryStream(imageBytes, 0, imageBytes.Length,true, true))
                    {
                        // byte[] buffer = pdfStream.GetBuffer();
                        XImage image = XImage.FromStream(imgStream);
                        using var gfx = XGraphics.FromPdfPage(page);
                        gfx.DrawImage(image, 0, 0, 100, 100);
                    }

                    using var newPdfStream = new MemoryStream();
                    document.Save(newPdfStream, false);
                    newPdfStream.Position = 0;
                    updatedPdfByte = newPdfStream.ToArray();
                }

**Comment by ThomasHoevel** [comment]
https://docs.pdfsharp.net/General/Issue-Reporting.html

**Comment by Suddenly-TurnRound** [comment]
> there have a problem in 6.1.0-preview-2
